CREATE TABLE `semed_school_classes` (
	`id` varchar(64) NOT NULL,
	`unit_inep` varchar(32) NOT NULL,
	`school_year` int NOT NULL,
	`school_name` varchar(255) NOT NULL,
	`class_name` varchar(160) NOT NULL,
	`class_type` varchar(160) NOT NULL,
	`students` int NOT NULL DEFAULT 0,
	`professionals` int NOT NULL DEFAULT 0,
	`source_row` varchar(96) NOT NULL,
	`source` varchar(160) NOT NULL,
	`imported_at` varchar(40) NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `semed_school_classes_id` PRIMARY KEY(`id`),
	CONSTRAINT `semed_school_classes_unit_year_name_uq` UNIQUE(`unit_inep`,`school_year`,`class_name`)
);
--> statement-breakpoint
CREATE TABLE `semed_school_units` (
	`id` varchar(64) NOT NULL,
	`code` varchar(96) NOT NULL,
	`name` varchar(255) NOT NULL,
	`school_type` varchar(160) NOT NULL,
	`type` varchar(48) NOT NULL,
	`status` enum('Ativa','Inativa') NOT NULL DEFAULT 'Ativa',
	`census_year` int NOT NULL,
	`neighborhood` varchar(160) NOT NULL,
	`address` text NOT NULL,
	`students` int NOT NULL DEFAULT 0,
	`has_uex` boolean NOT NULL DEFAULT false,
	`has_map` boolean NOT NULL DEFAULT false,
	`inep` varchar(32) NOT NULL,
	`email` varchar(320) NOT NULL,
	`manager_name` varchar(255) NOT NULL,
	`phone` varchar(64) NOT NULL,
	`notes` text NOT NULL,
	`enrollment_creche` int NOT NULL DEFAULT 0,
	`enrollment_pre_school` int NOT NULL DEFAULT 0,
	`enrollment_fundamental_1` int NOT NULL DEFAULT 0,
	`enrollment_fundamental_2` int NOT NULL DEFAULT 0,
	`enrollment_ejai_initial` int NOT NULL DEFAULT 0,
	`enrollment_ejai_final` int NOT NULL DEFAULT 0,
	`special_needs_creche` int NOT NULL DEFAULT 0,
	`special_needs_pre_school` int NOT NULL DEFAULT 0,
	`enrollment_grade_1` int NOT NULL DEFAULT 0,
	`special_needs_grade_1` int NOT NULL DEFAULT 0,
	`enrollment_grade_2` int NOT NULL DEFAULT 0,
	`special_needs_grade_2` int NOT NULL DEFAULT 0,
	`enrollment_grade_3` int NOT NULL DEFAULT 0,
	`special_needs_grade_3` int NOT NULL DEFAULT 0,
	`enrollment_grade_4` int NOT NULL DEFAULT 0,
	`special_needs_grade_4` int NOT NULL DEFAULT 0,
	`enrollment_grade_5` int NOT NULL DEFAULT 0,
	`special_needs_grade_5` int NOT NULL DEFAULT 0,
	`enrollment_grade_6` int NOT NULL DEFAULT 0,
	`special_needs_grade_6` int NOT NULL DEFAULT 0,
	`enrollment_grade_7` int NOT NULL DEFAULT 0,
	`special_needs_grade_7` int NOT NULL DEFAULT 0,
	`enrollment_grade_8` int NOT NULL DEFAULT 0,
	`special_needs_grade_8` int NOT NULL DEFAULT 0,
	`enrollment_grade_9` int NOT NULL DEFAULT 0,
	`special_needs_grade_9` int NOT NULL DEFAULT 0,
	`special_needs_ejai_initial` int NOT NULL DEFAULT 0,
	`special_needs_ejai_final` int NOT NULL DEFAULT 0,
	`property_type` varchar(120) NOT NULL,
	`location_zone` varchar(64) NOT NULL,
	`land_area_m2` int NOT NULL DEFAULT 0,
	`built_area_m2` int NOT NULL DEFAULT 0,
	`classrooms_total` int NOT NULL DEFAULT 0,
	`classrooms_in_use` int NOT NULL DEFAULT 0,
	`administrative_rooms` int NOT NULL DEFAULT 0,
	`bathrooms_total` int NOT NULL DEFAULT 0,
	`accessible_bathrooms` int NOT NULL DEFAULT 0,
	`kitchen_status` varchar(96) NOT NULL,
	`cafeteria_status` varchar(96) NOT NULL,
	`library_status` varchar(96) NOT NULL,
	`computer_lab_status` varchar(96) NOT NULL,
	`sports_court_status` varchar(96) NOT NULL,
	`accessibility_status` varchar(96) NOT NULL,
	`water_supply` varchar(160) NOT NULL,
	`energy_supply` varchar(160) NOT NULL,
	`sewage_system` varchar(160) NOT NULL,
	`internet_access` varchar(160) NOT NULL,
	`conservation_status` varchar(96) NOT NULL,
	`structure_notes` text NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `semed_school_units_id` PRIMARY KEY(`id`),
	CONSTRAINT `semed_school_units_code_uq` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE INDEX `semed_school_classes_unit_year_idx` ON `semed_school_classes` (`unit_inep`,`school_year`);--> statement-breakpoint
CREATE INDEX `semed_school_units_inep_idx` ON `semed_school_units` (`inep`);--> statement-breakpoint
CREATE INDEX `semed_school_units_status_year_idx` ON `semed_school_units` (`status`,`census_year`);