import React, { FormEvent, useMemo, useState } from "react";
import { BadgePercent, BookOpenCheck, CalendarDays, CircleDollarSign, Download, FileBarChart2, Landmark, Pencil, Plus, Printer, ReceiptText, RefreshCw, Scale, WalletCards, X } from "lucide-react";
import {
  SemedFinanceEntryStatus,
  SemedFinanceExecution,
  SemedFinanceExecutionInput,
  SemedFinancePlanningEntry,
  SemedFinancePlanningInput,
  SemedFinanceRevenue,
  SemedFinanceRevenueInput,
  SemedFinanceRule,
  SemedFinanceRuleInput,
  SemedFinanceSource,
  SemedFinanceSourceInput,
} from "./sigaLocalStore";
import "./siga-finance.css";

type FinanceSection = "overview" | "planning" | "revenues" | "execution" | "rules" | "reports";
type FormKind = "" | "planning" | "revenue" | "execution" | "source" | "rule";

type Props = {
  sources: SemedFinanceSource[];
  rules: SemedFinanceRule[];
  planningEntries: SemedFinancePlanningEntry[];
  revenues: SemedFinanceRevenue[];
  executions: SemedFinanceExecution[];
  contractCount: number;
  hrRecordCount: number;
  canWrite: boolean;
  canManageRules: boolean;
  onSaveSource: (input: SemedFinanceSourceInput) => { error: string | null; source: SemedFinanceSource | null };
  onSaveRule: (input: SemedFinanceRuleInput) => { error: string | null; rule: SemedFinanceRule | null };
  onSavePlanning: (input: SemedFinancePlanningInput) => { error: string | null; entry: SemedFinancePlanningEntry | null };
  onSaveRevenue: (input: SemedFinanceRevenueInput) => { error: string | null; revenue: SemedFinanceRevenue | null };
  onSaveExecution: (input: SemedFinanceExecutionInput) => { error: string | null; execution: SemedFinanceExecution | null };
  onNotify: (message: string) => void;
};

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const percent = new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 1, minimumFractionDigits: 1 });
const sections: { id: FinanceSection; label: string; icon: typeof Landmark }[] = [
  { id: "overview", label: "Visão geral", icon: Landmark }, { id: "planning", label: "Planejamento", icon: CalendarDays }, { id: "revenues", label: "Receitas", icon: CircleDollarSign },
  { id: "execution", label: "Execução", icon: WalletCards }, { id: "rules", label: "Fontes e regras", icon: Scale }, { id: "reports", label: "Relatórios", icon: FileBarChart2 },
];

const isActive = <T extends { status: SemedFinanceEntryStatus }>(entry: T) => entry.status === "Ativo";
const monthLabel = (value: string) => value ? new Date(`${value.slice(0, 7)}-01T12:00:00`).toLocaleDateString("pt-BR", { month: "short", year: "numeric" }).replace(".", "") : "—";
const dateLabel = (value: string) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR") : "—";

export default function SemedFinancePage(props: Props) {
  const [section, setSection] = useState<FinanceSection>("overview");
  const [year, setYear] = useState(2026);
  const [sourceFilter, setSourceFilter] = useState("");
  const [form, setForm] = useState<FormKind>("");
  const [editingPlanning, setEditingPlanning] = useState<SemedFinancePlanningEntry | null>(null);
  const [editingRevenue, setEditingRevenue] = useState<SemedFinanceRevenue | null>(null);
  const [editingExecution, setEditingExecution] = useState<SemedFinanceExecution | null>(null);
  const [editingSource, setEditingSource] = useState<SemedFinanceSource | null>(null);
  const [editingRule, setEditingRule] = useState<SemedFinanceRule | null>(null);

  const sources = useMemo(() => props.sources.filter((source) => source.active || source.id === sourceFilter), [props.sources, sourceFilter]);
  const sourceName = (id: string) => props.sources.find((source) => source.id === id)?.code ?? "Fonte demonstrativa";
  const inYear = (date: string) => date.startsWith(`${year}-`);
  const matchesSource = (sourceId: string) => !sourceFilter || sourceFilter === sourceId;
  const planning = useMemo(() => props.planningEntries.filter((entry) => inYear(entry.referenceMonth) && matchesSource(entry.sourceId)).sort((a, b) => b.referenceMonth.localeCompare(a.referenceMonth) || b.updatedAt.localeCompare(a.updatedAt)), [props.planningEntries, year, sourceFilter]);
  const revenues = useMemo(() => props.revenues.filter((entry) => inYear(entry.receiptDate) && matchesSource(entry.sourceId)).sort((a, b) => b.receiptDate.localeCompare(a.receiptDate) || b.updatedAt.localeCompare(a.updatedAt)), [props.revenues, year, sourceFilter]);
  const executions = useMemo(() => props.executions.filter((entry) => inYear(entry.executionDate) && matchesSource(entry.sourceId)).sort((a, b) => b.executionDate.localeCompare(a.executionDate) || b.updatedAt.localeCompare(a.updatedAt)), [props.executions, year, sourceFilter]);
  const sum = (values: number[]) => Math.round(values.reduce((total, value) => total + value, 0) * 100) / 100;
  const planned = sum(planning.filter(isActive).map((entry) => entry.plannedAmount));
  const revenueTotal = sum(revenues.filter(isActive).map((entry) => entry.amount));
  const committed = sum(executions.filter((entry) => isActive(entry) && entry.stage === "Empenhado").map((entry) => entry.amount));
  const settled = sum(executions.filter((entry) => isActive(entry) && entry.stage === "Liquidado").map((entry) => entry.amount));
  const paid = sum(executions.filter((entry) => isActive(entry) && entry.stage === "Pago").map((entry) => entry.amount));
  const opening = sum(props.sources.filter((source) => !sourceFilter || source.id === sourceFilter).map((source) => source.openingBalance));
  const availability = opening + revenueTotal - paid;
  const years = useMemo(() => Array.from(new Set([2024, 2025, 2026, 2027, 2028, ...props.rules.map((rule) => rule.referenceYear), ...props.planningEntries.map((entry) => Number(entry.referenceMonth.slice(0, 4)))] )).sort(), [props.rules, props.planningEntries]);
  const activeRules = props.rules.filter((rule) => rule.active && rule.referenceYear === year);
  const indicators = activeRules.map((rule) => {
    const sourceCode = rule.code.split("_")[0];
    const source = props.sources.find((item) => item.code === sourceCode);
    const base = source ? sum(props.revenues.filter((entry) => isActive(entry) && entry.sourceId === source.id && inYear(entry.receiptDate)).map((entry) => entry.amount)) : 0;
    const applied = sum(props.executions.filter((entry) => isActive(entry) && entry.stage === "Apropriação legal" && entry.classification === rule.code && inYear(entry.executionDate)).map((entry) => entry.amount));
    const actual = base ? applied * 100 / base : 0;
    return { rule, actual, applied, meets: actual >= rule.targetPercentage };
  });
  const monthly = Array.from({ length: 12 }, (_, index) => {
    const reference = `${year}-${String(index + 1).padStart(2, "0")}`;
    const received = sum(props.revenues.filter((entry) => isActive(entry) && matchesSource(entry.sourceId) && entry.receiptDate.startsWith(reference)).map((entry) => entry.amount));
    const payments = sum(props.executions.filter((entry) => isActive(entry) && matchesSource(entry.sourceId) && entry.stage === "Pago" && entry.executionDate.startsWith(reference)).map((entry) => entry.amount));
    return { reference, received, payments };
  });

  function resetForm() { setForm(""); setEditingPlanning(null); setEditingRevenue(null); setEditingExecution(null); setEditingSource(null); setEditingRule(null); }
  function openForm(kind: FormKind, entry?: SemedFinancePlanningEntry | SemedFinanceRevenue | SemedFinanceExecution | SemedFinanceSource | SemedFinanceRule) {
    resetForm();
    if (kind === "planning") setEditingPlanning(entry as SemedFinancePlanningEntry ?? null);
    if (kind === "revenue") setEditingRevenue(entry as SemedFinanceRevenue ?? null);
    if (kind === "execution") setEditingExecution(entry as SemedFinanceExecution ?? null);
    if (kind === "source") setEditingSource(entry as SemedFinanceSource ?? null);
    if (kind === "rule") setEditingRule(entry as SemedFinanceRule ?? null);
    setForm(kind);
  }
  function cancelPlanning(entry: SemedFinancePlanningEntry) { const result = props.onSavePlanning({ ...entry, status: "Cancelado" }); result.error ? props.onNotify(result.error) : props.onNotify("Planejamento cancelado e preservado na auditoria local."); }
  function cancelRevenue(entry: SemedFinanceRevenue) { const result = props.onSaveRevenue({ ...entry, status: "Cancelado" }); result.error ? props.onNotify(result.error) : props.onNotify("Receita cancelada e preservada na auditoria local."); }
  function cancelExecution(entry: SemedFinanceExecution) { const result = props.onSaveExecution({ ...entry, status: "Cancelado" }); result.error ? props.onNotify(result.error) : props.onNotify("Execução cancelada e preservada na auditoria local."); }
  function exportCsv() {
    const rows = props.sources.filter((source) => !sourceFilter || source.id === sourceFilter).map((source) => {
      const sourcePlanning = sum(props.planningEntries.filter((entry) => isActive(entry) && entry.sourceId === source.id && inYear(entry.referenceMonth)).map((entry) => entry.plannedAmount));
      const sourceRevenue = sum(props.revenues.filter((entry) => isActive(entry) && entry.sourceId === source.id && inYear(entry.receiptDate)).map((entry) => entry.amount));
      const sourceCommitted = sum(props.executions.filter((entry) => isActive(entry) && entry.sourceId === source.id && inYear(entry.executionDate) && entry.stage === "Empenhado").map((entry) => entry.amount));
      const sourceSettled = sum(props.executions.filter((entry) => isActive(entry) && entry.sourceId === source.id && inYear(entry.executionDate) && entry.stage === "Liquidado").map((entry) => entry.amount));
      const sourcePaid = sum(props.executions.filter((entry) => isActive(entry) && entry.sourceId === source.id && inYear(entry.executionDate) && entry.stage === "Pago").map((entry) => entry.amount));
      return [source.code, sourcePlanning, sourceRevenue, sourceCommitted, sourceSettled, sourcePaid, source.openingBalance + sourceRevenue - sourcePaid];
    });
    const csv = [["Fonte", "Planejado", "Receitas", "Empenhado", "Liquidado", "Pago", "Disponível"], ...rows].map((row) => row.join(";")).join("\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `financeiro-local-${year}.csv`; anchor.click(); URL.revokeObjectURL(url);
    props.onNotify("CSV financeiro local preparado com os filtros ativos.");
  }

  const currentTitle = sections.find((item) => item.id === section)?.label ?? "Financeiro";
  return <section className="siga-finance-page" aria-label="Módulo Financeiro">
    <header className="siga-finance-hero"><div className="siga-finance-hero-icon"><Landmark size={21} /></div><div><small>Planejamento e execução</small><h1>Financeiro</h1><p>Visão consolidada de fontes, receitas, despesas e regras locais demonstrativas.</p></div><div className="siga-finance-tools"><label>Exercício<select value={year} onChange={(event) => setYear(Number(event.target.value))}>{years.map((value) => <option key={value}>{value}</option>)}</select></label><label>Fonte<select value={sourceFilter} onChange={(event) => setSourceFilter(event.target.value)}><option value="">Todas as fontes</option>{sources.map((source) => <option key={source.id} value={source.id}>{source.code}</option>)}</select></label><button type="button" title="Atualizar visão local" onClick={() => props.onNotify("Dados financeiros locais atualizados.")}><RefreshCw size={16} /></button><button type="button" title="Imprimir relatório local" onClick={() => { window.print(); props.onNotify("Relatório financeiro local enviado para impressão."); }}><Printer size={16} /></button></div></header>
    <section className="siga-finance-metrics"><Metric label="Planejado" value={money.format(planned)} tone="blue" /><Metric label="Receitas" value={money.format(revenueTotal)} tone="green" /><Metric label="Empenhado" value={money.format(committed)} tone="orange" /><Metric label="Liquidado" value={money.format(settled)} tone="slate" /><Metric label="Pago" value={money.format(paid)} tone="pink" /><Metric label="Disponibilidade" value={money.format(availability)} tone={availability >= 0 ? "green" : "red"} /></section>
    <nav className="siga-finance-tabs" aria-label="Áreas financeiras">{sections.map((item) => <button key={item.id} type="button" className={section === item.id ? "active" : ""} onClick={() => { setSection(item.id); resetForm(); }}><item.icon size={15} />{item.label}</button>)}</nav>
    {!props.canWrite ? <p className="siga-workspace-notice">Perfil em modo somente leitura neste módulo financeiro.</p> : null}
    {form === "planning" ? <PlanningForm initial={editingPlanning} sources={sources} onCancel={resetForm} onSave={(input) => { const result = props.onSavePlanning(input); if (result.error) props.onNotify(result.error); else { resetForm(); props.onNotify("Planejamento salvo somente no Financeiro local."); } }} /> : null}
    {form === "revenue" ? <RevenueForm initial={editingRevenue} sources={sources} onCancel={resetForm} onSave={(input) => { const result = props.onSaveRevenue(input); if (result.error) props.onNotify(result.error); else { resetForm(); props.onNotify("Receita salva somente no Financeiro local."); } }} /> : null}
    {form === "execution" ? <ExecutionForm initial={editingExecution} sources={sources} onCancel={resetForm} onSave={(input) => { const result = props.onSaveExecution(input); if (result.error) props.onNotify(result.error); else { resetForm(); props.onNotify("Execução salva somente no Financeiro local."); } }} /> : null}
    {form === "source" ? <SourceForm initial={editingSource} onCancel={resetForm} onSave={(input) => { const result = props.onSaveSource(input); if (result.error) props.onNotify(result.error); else { resetForm(); props.onNotify("Fonte salva somente no Financeiro local."); } }} /> : null}
    {form === "rule" ? <RuleForm initial={editingRule} onCancel={resetForm} onSave={(input) => { const result = props.onSaveRule(input); if (result.error) props.onNotify(result.error); else { resetForm(); props.onNotify("Regra salva somente no Financeiro local."); } }} /> : null}
    {section === "overview" ? <OverviewPanel indicators={indicators} monthly={monthly} contractCount={props.contractCount} hrRecordCount={props.hrRecordCount} /> : null}
    {section === "planning" ? <EntryTable title="Planejamento anual" description="Programação mensal por fonte, programa, ação e natureza da despesa." count={planning.length} canWrite={props.canWrite} onNew={() => openForm("planning")} headers={["Mês", "Fonte", "Programa", "Descrição", "Natureza", "Planejado", "Situação", ""]} rows={planning.map((entry) => <tr key={entry.id}><td>{monthLabel(entry.referenceMonth)}</td><td>{sourceName(entry.sourceId)}</td><td>{entry.program}</td><td>{entry.description}</td><td>{entry.expenseNature}</td><td>{money.format(entry.plannedAmount)}</td><td><Status value={entry.status} /></td><td><RowActions enabled={props.canWrite && entry.status === "Ativo"} onEdit={() => openForm("planning", entry)} onCancel={() => cancelPlanning(entry)} /></td></tr>)} empty="Nenhum planejamento local encontrado para os filtros." /> : null}
    {section === "revenues" ? <EntryTable title="Receitas e repasses" description="Créditos, rendimentos, saldos reprogramados e contrapartidas locais." count={revenues.length} canWrite={props.canWrite} onNew={() => openForm("revenue")} headers={["Data", "Fonte", "Componente", "Tipo", "Referência", "Valor", "Situação", ""]} rows={revenues.map((entry) => <tr key={entry.id}><td>{dateLabel(entry.receiptDate)}</td><td>{sourceName(entry.sourceId)}</td><td>{entry.component}</td><td>{entry.type}</td><td>{entry.reference}</td><td>{money.format(entry.amount)}</td><td><Status value={entry.status} /></td><td><RowActions enabled={props.canWrite && entry.status === "Ativo"} onEdit={() => openForm("revenue", entry)} onCancel={() => cancelRevenue(entry)} /></td></tr>)} empty="Nenhuma receita local encontrada para os filtros." /> : null}
    {section === "execution" ? <EntryTable title="Execução da despesa" description="Registre empenho, liquidação, pagamento ou apropriação legal demonstrativa." count={executions.length} canWrite={props.canWrite} onNew={() => openForm("execution")} headers={["Data", "Fonte", "Etapa", "Descrição", "Classificação", "Documento", "Valor", "Situação", ""]} rows={executions.map((entry) => <tr key={entry.id}><td>{dateLabel(entry.executionDate)}</td><td>{sourceName(entry.sourceId)}</td><td>{entry.stage}</td><td>{entry.description}</td><td>{entry.classification}</td><td>{entry.documentReference}</td><td>{money.format(entry.amount)}</td><td><Status value={entry.status} /></td><td><RowActions enabled={props.canWrite && entry.status === "Ativo"} onEdit={() => openForm("execution", entry)} onCancel={() => cancelExecution(entry)} /></td></tr>)} empty="Nenhuma execução local encontrada para os filtros." /> : null}
    {section === "rules" ? <RulesPanel sources={sources} rules={activeRules} canManage={props.canManageRules} onNewSource={() => openForm("source")} onNewRule={() => openForm("rule")} onEditSource={(entry) => openForm("source", entry)} onEditRule={(entry) => openForm("rule", entry)} /> : null}
    {section === "reports" ? <ReportsPanel sources={props.sources} year={year} sourceFilter={sourceFilter} planning={props.planningEntries} revenues={props.revenues} executions={props.executions} onExport={exportCsv} /> : null}
    <p className="siga-finance-note">{currentTitle}: consultas, fórmulas, CSV e impressão usam exclusivamente registros demonstrativos persistidos no navegador.</p>
  </section>;
}

function Metric({ label, value, tone }: { label: string; value: string; tone: string }) { return <article className={`siga-finance-metric ${tone}`}><span>{label}</span><strong>{value}</strong></article>; }
function Status({ value }: { value: SemedFinanceEntryStatus }) { return <span className={`siga-finance-status ${value === "Ativo" ? "active" : "cancelled"}`}>{value}</span>; }
function RowActions({ enabled, onEdit, onCancel }: { enabled: boolean; onEdit: () => void; onCancel: () => void }) { return enabled ? <span className="siga-finance-row-actions"><button type="button" title="Editar" onClick={onEdit}><Pencil size={14} /></button><button type="button" title="Cancelar lançamento" onClick={onCancel}><X size={15} /></button></span> : null; }
function EntryTable({ title, description, count, canWrite, onNew, headers, rows, empty }: { title: string; description: string; count: number; canWrite: boolean; onNew: () => void; headers: string[]; rows: React.ReactNode[]; empty: string }) { return <section className="siga-finance-panel"><div className="siga-list-heading"><div><p>Financeiro local</p><h2>{title}</h2><span>{description}</span></div>{canWrite ? <button type="button" className="siga-primary-button" onClick={onNew}><Plus size={15} />Novo cadastro</button> : <span>{count} registro(s)</span>}</div><div className="siga-finance-table-wrap"><table><thead><tr>{headers.map((header, index) => <th key={`${header}-${index}`}>{header}</th>)}</tr></thead><tbody>{rows}</tbody></table>{!count ? <p className="siga-finance-empty">{empty}</p> : null}</div></section>; }

function OverviewPanel({ indicators, monthly, contractCount, hrRecordCount }: { indicators: { rule: SemedFinanceRule; actual: number; applied: number; meets: boolean }[]; monthly: { reference: string; received: number; payments: number }[]; contractCount: number; hrRecordCount: number }) { return <><section className="siga-finance-overview-grid"><article className="siga-finance-legal"><div className="siga-list-heading"><div><p>Aplicações e metas</p><h2>Indicadores legais</h2></div><BadgePercent size={20} /></div>{indicators.map(({ rule, actual, meets }) => <div className="siga-finance-rule-progress" key={rule.id}><span><strong>{rule.name}</strong><small>{percent.format(actual)}% · meta {percent.format(rule.targetPercentage)}%</small></span><div><i style={{ width: `${Math.min(100, actual)}%` }} className={meets ? "good" : "warning"} /></div></div>)}{!indicators.length ? <p className="siga-finance-empty">Nenhuma regra demonstrativa ativa para o exercício.</p> : null}</article><article className="siga-finance-integrations"><div className="siga-list-heading"><div><p>Integrações do SIGA</p><h2>Consultas locais</h2></div><BookOpenCheck size={20} /></div><div><span><ReceiptText size={17} /><small>Contratos</small><strong>{contractCount} registro(s)</strong></span><span><WalletCards size={17} /><small>RH · fichas</small><strong>{hrRecordCount} registro(s)</strong></span><span><CircleDollarSign size={17} /><small>Execução</small><strong>{monthly.filter((entry) => entry.payments > 0).length} mês(es)</strong></span></div></article></section><section className="siga-finance-monthly"><div className="siga-list-heading"><div><p>Receitas e pagamentos</p><h2>Execução mensal</h2></div></div><div>{monthly.map((entry) => <article key={entry.reference}><small>{monthLabel(entry.reference)}</small><strong>{money.format(entry.received)}</strong><span>Pago {money.format(entry.payments)}</span></article>)}</div></section></>; }

function RulesPanel({ sources, rules, canManage, onNewSource, onNewRule, onEditSource, onEditRule }: { sources: SemedFinanceSource[]; rules: SemedFinanceRule[]; canManage: boolean; onNewSource: () => void; onNewRule: () => void; onEditSource: (source: SemedFinanceSource) => void; onEditRule: (rule: SemedFinanceRule) => void }) { return <><section className="siga-finance-panel"><div className="siga-list-heading"><div><p>Origens e saldos</p><h2>Fontes de recursos</h2></div>{canManage ? <button type="button" className="siga-primary-button" onClick={onNewSource}><Plus size={15} />Nova fonte</button> : null}</div><div className="siga-finance-source-grid">{sources.map((source) => <article key={source.id}><span>{source.code}</span><strong>{source.name}</strong><small>{source.category}</small><b>Saldo inicial {money.format(source.openingBalance)}</b>{canManage ? <button type="button" onClick={() => onEditSource(source)}><Pencil size={14} />Editar fonte</button> : null}</article>)}{!sources.length ? <p className="siga-finance-empty">Nenhuma fonte local ativa para o filtro.</p> : null}</div></section><section className="siga-finance-panel"><div className="siga-list-heading"><div><p>Parâmetros versionados</p><h2>Regras do exercício</h2><span>Alterações são restritas a Administrador.</span></div>{canManage ? <button type="button" className="siga-secondary-button" onClick={onNewRule}><Plus size={15} />Nova regra</button> : null}</div><div className="siga-finance-table-wrap"><table><thead><tr><th>Código</th><th>Regra</th><th>Percentual</th><th>Observação</th><th /></tr></thead><tbody>{rules.map((rule) => <tr key={rule.id}><td>{rule.code}</td><td>{rule.name}</td><td>{percent.format(rule.targetPercentage)}%</td><td>{rule.description || "—"}</td><td>{canManage ? <button type="button" className="siga-finance-icon-button" onClick={() => onEditRule(rule)}><Pencil size={14} /></button> : null}</td></tr>)}</tbody></table>{!rules.length ? <p className="siga-finance-empty">Nenhuma regra demonstrativa ativa neste exercício.</p> : null}</div></section></>; }

function ReportsPanel({ sources, year, sourceFilter, planning, revenues, executions, onExport }: { sources: SemedFinanceSource[]; year: number; sourceFilter: string; planning: SemedFinancePlanningEntry[]; revenues: SemedFinanceRevenue[]; executions: SemedFinanceExecution[]; onExport: () => void }) { const sum = (values: number[]) => values.reduce((total, value) => total + value, 0); const active = <T extends { status: SemedFinanceEntryStatus }>(entries: T[]) => entries.filter(isActive); const sourceRows = sources.filter((source) => !sourceFilter || source.id === sourceFilter).map((source) => { const inYear = (date: string) => date.startsWith(`${year}-`); const planned = sum(active(planning).filter((entry) => entry.sourceId === source.id && inYear(entry.referenceMonth)).map((entry) => entry.plannedAmount)); const revenue = sum(active(revenues).filter((entry) => entry.sourceId === source.id && inYear(entry.receiptDate)).map((entry) => entry.amount)); const stage = (name: SemedFinanceExecution["stage"]) => sum(active(executions).filter((entry) => entry.sourceId === source.id && inYear(entry.executionDate) && entry.stage === name).map((entry) => entry.amount)); const paid = stage("Pago"); return { source, planned, revenue, committed: stage("Empenhado"), settled: stage("Liquidado"), paid, available: source.openingBalance + revenue - paid }; }); return <section className="siga-finance-panel"><div className="siga-list-heading"><div><p>Base para impressão</p><h2>Relatório da execução</h2><span>Consolidado por fonte com planejamento, receita e etapas da despesa.</span></div><button type="button" className="siga-secondary-button" onClick={onExport}><Download size={15} />CSV</button></div><div className="siga-finance-table-wrap"><table><thead><tr><th>Fonte</th><th>Planejado</th><th>Receita</th><th>Empenhado</th><th>Liquidado</th><th>Pago</th><th>Disponível</th></tr></thead><tbody>{sourceRows.map(({ source, planned, revenue, committed, settled, paid, available }) => <tr key={source.id}><td><strong>{source.code}</strong><small>{source.name}</small></td><td>{money.format(planned)}</td><td>{money.format(revenue)}</td><td>{money.format(committed)}</td><td>{money.format(settled)}</td><td>{money.format(paid)}</td><td>{money.format(available)}</td></tr>)}</tbody></table></div></section>; }

function PlanningForm({ initial, sources, onCancel, onSave }: { initial: SemedFinancePlanningEntry | null; sources: SemedFinanceSource[]; onCancel: () => void; onSave: (input: SemedFinancePlanningInput) => void }) { return <form className="siga-data-form siga-finance-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave({ id: initial?.id, referenceMonth: String(form.get("referenceMonth") ?? ""), sourceId: String(form.get("sourceId") ?? ""), program: String(form.get("program") ?? ""), description: String(form.get("description") ?? ""), expenseNature: String(form.get("expenseNature") ?? ""), plannedAmount: Number(form.get("plannedAmount") ?? 0), status: form.get("status") as SemedFinanceEntryStatus }); }}><FormHeading title={initial ? "Editar planejamento" : "Novo planejamento"} onCancel={onCancel} /><div className="siga-form-two"><label>Competência<input name="referenceMonth" type="month" required defaultValue={initial?.referenceMonth ?? "2026-01"} /></label><label>Fonte<select name="sourceId" defaultValue={initial?.sourceId}>{sources.map((source) => <option key={source.id} value={source.id}>{source.code}</option>)}</select></label></div><label>Programa<input name="program" required defaultValue={initial?.program} placeholder="Programa demonstrativo" /></label><label>Descrição<input name="description" required defaultValue={initial?.description} placeholder="Finalidade demonstrativa" /></label><div className="siga-form-two"><label>Natureza<input name="expenseNature" required defaultValue={initial?.expenseNature} placeholder="Custeio, capital ou pessoal" /></label><label>Planejado<input name="plannedAmount" type="number" min="0.01" step="0.01" required defaultValue={initial?.plannedAmount ?? ""} /></label></div><StatusField value={initial?.status} /><FormActions onCancel={onCancel} /></form>; }
function RevenueForm({ initial, sources, onCancel, onSave }: { initial: SemedFinanceRevenue | null; sources: SemedFinanceSource[]; onCancel: () => void; onSave: (input: SemedFinanceRevenueInput) => void }) { return <form className="siga-data-form siga-finance-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave({ id: initial?.id, receiptDate: String(form.get("receiptDate") ?? ""), sourceId: String(form.get("sourceId") ?? ""), component: String(form.get("component") ?? ""), type: form.get("type") as SemedFinanceRevenueInput["type"], reference: String(form.get("reference") ?? ""), amount: Number(form.get("amount") ?? 0), status: form.get("status") as SemedFinanceEntryStatus }); }}><FormHeading title={initial ? "Editar receita" : "Nova receita"} onCancel={onCancel} /><div className="siga-form-two"><label>Data<input name="receiptDate" type="date" required defaultValue={initial?.receiptDate ?? "2026-01-05"} /></label><label>Fonte<select name="sourceId" defaultValue={initial?.sourceId}>{sources.map((source) => <option key={source.id} value={source.id}>{source.code}</option>)}</select></label></div><div className="siga-form-two"><label>Componente<input name="component" required defaultValue={initial?.component} placeholder="Repasse demonstrativo" /></label><label>Tipo<select name="type" defaultValue={initial?.type ?? "Repasse"}><option>Repasse</option><option>Rendimento</option><option>Saldo reprogramado</option><option>Contrapartida</option></select></label></div><div className="siga-form-two"><label>Referência<input name="reference" required defaultValue={initial?.reference} placeholder="Referência local" /></label><label>Valor<input name="amount" type="number" min="0.01" step="0.01" required defaultValue={initial?.amount ?? ""} /></label></div><StatusField value={initial?.status} /><FormActions onCancel={onCancel} /></form>; }
function ExecutionForm({ initial, sources, onCancel, onSave }: { initial: SemedFinanceExecution | null; sources: SemedFinanceSource[]; onCancel: () => void; onSave: (input: SemedFinanceExecutionInput) => void }) { return <form className="siga-data-form siga-finance-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave({ id: initial?.id, executionDate: String(form.get("executionDate") ?? ""), sourceId: String(form.get("sourceId") ?? ""), stage: form.get("stage") as SemedFinanceExecutionInput["stage"], description: String(form.get("description") ?? ""), classification: String(form.get("classification") ?? ""), documentReference: String(form.get("documentReference") ?? ""), amount: Number(form.get("amount") ?? 0), status: form.get("status") as SemedFinanceEntryStatus }); }}><FormHeading title={initial ? "Editar execução" : "Nova execução"} onCancel={onCancel} /><div className="siga-form-two"><label>Data<input name="executionDate" type="date" required defaultValue={initial?.executionDate ?? "2026-01-12"} /></label><label>Fonte<select name="sourceId" defaultValue={initial?.sourceId}>{sources.map((source) => <option key={source.id} value={source.id}>{source.code}</option>)}</select></label></div><div className="siga-form-two"><label>Etapa<select name="stage" defaultValue={initial?.stage ?? "Empenhado"}><option>Empenhado</option><option>Liquidado</option><option>Pago</option><option>Apropriação legal</option></select></label><label>Classificação<input name="classification" required defaultValue={initial?.classification} placeholder="Ex.: FUNDEB_70" /></label></div><label>Descrição<input name="description" required defaultValue={initial?.description} placeholder="Despesa demonstrativa" /></label><div className="siga-form-two"><label>Documento<input name="documentReference" required defaultValue={initial?.documentReference} placeholder="DOC-DEMO-001" /></label><label>Valor<input name="amount" type="number" min="0.01" step="0.01" required defaultValue={initial?.amount ?? ""} /></label></div><StatusField value={initial?.status} /><FormActions onCancel={onCancel} /></form>; }
function SourceForm({ initial, onCancel, onSave }: { initial: SemedFinanceSource | null; onCancel: () => void; onSave: (input: SemedFinanceSourceInput) => void }) { return <form className="siga-data-form siga-finance-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave({ id: initial?.id, code: String(form.get("code") ?? ""), name: String(form.get("name") ?? ""), category: String(form.get("category") ?? ""), openingBalance: Number(form.get("openingBalance") ?? 0), active: form.get("active") === "on" }); }}><FormHeading title={initial ? "Editar fonte" : "Nova fonte"} onCancel={onCancel} /><div className="siga-form-two"><label>Código<input name="code" required defaultValue={initial?.code} placeholder="SIGLA" /></label><label>Categoria<input name="category" required defaultValue={initial?.category} placeholder="Fundo, programa ou convênio" /></label></div><label>Nome<input name="name" required defaultValue={initial?.name} placeholder="Fonte demonstrativa" /></label><label>Saldo inicial<input name="openingBalance" type="number" min="0" step="0.01" defaultValue={initial?.openingBalance ?? 0} /></label><label className="siga-check"><input name="active" type="checkbox" defaultChecked={initial?.active ?? true} />Fonte ativa</label><FormActions onCancel={onCancel} /></form>; }
function RuleForm({ initial, onCancel, onSave }: { initial: SemedFinanceRule | null; onCancel: () => void; onSave: (input: SemedFinanceRuleInput) => void }) { return <form className="siga-data-form siga-finance-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave({ id: initial?.id, code: String(form.get("code") ?? ""), name: String(form.get("name") ?? ""), targetPercentage: Number(form.get("targetPercentage") ?? 0), description: String(form.get("description") ?? ""), referenceYear: Number(form.get("referenceYear") ?? 0), active: form.get("active") === "on" }); }}><FormHeading title={initial ? "Editar regra" : "Nova regra"} onCancel={onCancel} /><div className="siga-form-two"><label>Código<input name="code" required defaultValue={initial?.code} placeholder="REGRA_XX" /></label><label>Exercício<input name="referenceYear" type="number" min="2020" max="2100" required defaultValue={initial?.referenceYear ?? 2026} /></label></div><label>Regra<input name="name" required defaultValue={initial?.name} placeholder="Meta demonstrativa" /></label><label>Percentual alvo<input name="targetPercentage" type="number" min="0" max="100" step="0.01" required defaultValue={initial?.targetPercentage ?? ""} /></label><label>Observação<textarea name="description" rows={2} defaultValue={initial?.description} /></label><label className="siga-check"><input name="active" type="checkbox" defaultChecked={initial?.active ?? true} />Regra ativa</label><FormActions onCancel={onCancel} /></form>; }
function FormHeading({ title, onCancel }: { title: string; onCancel: () => void }) { return <div className="siga-form-heading"><div><h2>{title}</h2><span>Registro demonstrativo persistido somente no navegador.</span></div><button type="button" className="siga-finance-icon-button" onClick={onCancel}><X size={16} /></button></div>; }
function StatusField({ value }: { value?: SemedFinanceEntryStatus }) { return <label>Situação<select name="status" defaultValue={value ?? "Ativo"}><option>Ativo</option><option>Cancelado</option></select></label>; }
function FormActions({ onCancel }: { onCancel: () => void }) { return <div className="siga-form-actions"><button type="button" className="siga-secondary-button" onClick={onCancel}>Cancelar</button><button type="submit" className="siga-primary-button">Salvar localmente</button></div>; }
