import { FormEvent, useMemo, useState } from "react";
import React from "react";
import { AlertTriangle, CarFront, ClipboardList, Download, Fuel, Gauge, PenLine, Printer, Save, Settings2, Wrench, X } from "lucide-react";
import type { SemedFleetFuel, SemedFleetFuelInput, SemedFleetMaintenance, SemedFleetMaintenanceInput, SemedFleetOccurrence, SemedFleetOccurrenceInput, SemedFleetVehicle, SemedFleetVehicleInput } from "./sigaLocalStore";
import "./siga-fleet.css";

export type FleetSection = "vehicles" | "fuel" | "maintenance" | "occurrences" | "reports";
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const dateLabel = (value: string) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR") : "—";
const currentDate = () => new Date().toISOString().slice(0, 10);

const blankVehicle = (): SemedFleetVehicleInput => ({ code: "", patrimony: "", plate: "", model: "", category: "", status: "Ativo", odometerKm: 0, capacity: 5, responsibleUserId: "u-tecnico1", costCenter: "", recordId: "", documentId: "", sourceId: "" });
const blankFuel = (): SemedFleetFuelInput => ({ vehicleId: "", fuelDate: currentDate(), odometerKm: 0, liters: 0, unitPrice: 0, supplier: "", responsibleUserId: "u-tecnico1", documentReference: "", recordId: "", documentId: "", sourceId: "", status: "Registrado" });
const blankMaintenance = (): SemedFleetMaintenanceInput => ({ vehicleId: "", maintenanceDate: currentDate(), odometerKm: 0, type: "Preventiva", supplier: "", cost: 0, nextDate: "", nextOdometerKm: 0, description: "", responsibleUserId: "u-tecnico1", recordId: "", documentId: "", sourceId: "", status: "Agendada" });
const blankOccurrence = (): SemedFleetOccurrenceInput => ({ vehicleId: "", occurrenceDate: currentDate(), type: "Avaria", status: "Aberta", location: "", responsibleUserId: "u-tecnico1", description: "", resolution: "", recordId: "", documentId: "" });

export default function SemedFleetPage({ vehicles, fuelLogs, maintenances, occurrences, actorUserId, canWrite, onSaveVehicle, onSaveFuel, onSaveMaintenance, onSaveOccurrence, onNotify }: {
  vehicles: SemedFleetVehicle[]; fuelLogs: SemedFleetFuel[]; maintenances: SemedFleetMaintenance[]; occurrences: SemedFleetOccurrence[]; actorUserId: string; canWrite: boolean;
  onSaveVehicle: (input: SemedFleetVehicleInput) => { error: string | null; vehicle: SemedFleetVehicle | null };
  onSaveFuel: (input: SemedFleetFuelInput) => { error: string | null; fuel: SemedFleetFuel | null };
  onSaveMaintenance: (input: SemedFleetMaintenanceInput) => { error: string | null; maintenance: SemedFleetMaintenance | null };
  onSaveOccurrence: (input: SemedFleetOccurrenceInput) => { error: string | null; occurrence: SemedFleetOccurrence | null };
  onNotify: (message: string) => void;
}) {
  const [section, setSection] = useState<FleetSection>("vehicles");
  const [query, setQuery] = useState("");
  const [vehicleForm, setVehicleForm] = useState<SemedFleetVehicleInput>(blankVehicle);
  const [fuelForm, setFuelForm] = useState<SemedFleetFuelInput>(blankFuel);
  const [maintenanceForm, setMaintenanceForm] = useState<SemedFleetMaintenanceInput>(blankMaintenance);
  const [occurrenceForm, setOccurrenceForm] = useState<SemedFleetOccurrenceInput>(blankOccurrence);
  const [editing, setEditing] = useState<"vehicle" | "fuel" | "maintenance" | "occurrence" | null>(null);

  const vehicleName = (id: string) => { const vehicle = vehicles.find((item) => item.id === id); return vehicle ? `${vehicle.code} · ${vehicle.model}` : "Veículo não localizado"; };
  const filteredVehicles = useMemo(() => vehicles.filter((vehicle) => `${vehicle.code} ${vehicle.plate} ${vehicle.model} ${vehicle.patrimony}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [vehicles, query]);
  const totalFuel = fuelLogs.filter((item) => item.status !== "Cancelado").reduce((sum, item) => sum + item.totalAmount, 0);
  const openOccurrences = occurrences.filter((item) => item.status !== "Resolvida").length;
  const pendingMaintenance = maintenances.filter((item) => item.status === "Agendada").length;

  function saveVehicle(event: FormEvent) { event.preventDefault(); const result = onSaveVehicle(vehicleForm); if (result.error) return onNotify(result.error); setVehicleForm(blankVehicle()); setEditing(null); onNotify("Veículo salvo somente no armazenamento local."); }
  function saveFuel(event: FormEvent) { event.preventDefault(); const result = onSaveFuel(fuelForm); if (result.error) return onNotify(result.error); setFuelForm(blankFuel()); setEditing(null); onNotify("Abastecimento salvo somente no armazenamento local."); }
  function saveMaintenance(event: FormEvent) { event.preventDefault(); const result = onSaveMaintenance(maintenanceForm); if (result.error) return onNotify(result.error); setMaintenanceForm(blankMaintenance()); setEditing(null); onNotify("Manutenção salva somente no armazenamento local."); }
  function saveOccurrence(event: FormEvent) { event.preventDefault(); const result = onSaveOccurrence(occurrenceForm); if (result.error) return onNotify(result.error); setOccurrenceForm(blankOccurrence()); setEditing(null); onNotify("Ocorrência salva somente no armazenamento local."); }
  function exportReport() { const rows = [["Veículo", "Situação", "Km", "Abastecimentos", "Manutenções", "Ocorrências"], ...vehicles.map((vehicle) => [vehicle.code, vehicle.status, String(vehicle.odometerKm), String(fuelLogs.filter((item) => item.vehicleId === vehicle.id).length), String(maintenances.filter((item) => item.vehicleId === vehicle.id).length), String(occurrences.filter((item) => item.vehicleId === vehicle.id).length)])]; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([rows.map((row) => row.map((cell) => `"${cell}"`).join(";")).join("\n")], { type: "text/csv;charset=utf-8" })); link.download = "relatorio-frota-demonstrativo.csv"; link.click(); URL.revokeObjectURL(link.href); }

  const sections: { id: FleetSection; label: string; icon: typeof CarFront }[] = [
    { id: "vehicles", label: "Cadastro de veículos", icon: CarFront }, { id: "fuel", label: "Abastecimento", icon: Fuel }, { id: "maintenance", label: "Manutenção", icon: Wrench }, { id: "occurrences", label: "Ocorrências", icon: AlertTriangle }, { id: "reports", label: "Relatórios", icon: ClipboardList },
  ];

  return <section className="siga-fleet-page" aria-labelledby="fleet-title">
    <header className="siga-fleet-hero"><div><p><CarFront size={15} /> Operação demonstrativa</p><h1 id="fleet-title">Frota</h1><span>Veículos, abastecimentos, manutenções e ocorrências integrados à auditoria local.</span></div><div className="siga-fleet-hero-state"><Gauge size={20} /><strong>{vehicles.filter((item) => item.status === "Ativo").length} veículos ativos</strong><small>Dados próprios do preview</small></div></header>
    <div className="siga-fleet-metrics"><Metric icon={<CarFront />} label="Veículos cadastrados" value={vehicles.length} tone="green" /><Metric icon={<Fuel />} label="Abastecimento registrado" value={money.format(totalFuel)} tone="blue" /><Metric icon={<Wrench />} label="Manutenções agendadas" value={pendingMaintenance} tone="orange" /><Metric icon={<AlertTriangle />} label="Ocorrências em aberto" value={openOccurrences} tone="pink" /></div>
    <nav className="siga-fleet-tabs" aria-label="Seções de Frota">{sections.map(({ id, label, icon: Icon }) => <button key={id} type="button" className={section === id ? "is-active" : ""} onClick={() => setSection(id)}><Icon size={16} />{label}</button>)}</nav>
    {!canWrite ? <div className="siga-fleet-readonly"><Settings2 size={17} /> Este perfil possui consulta de Frota. Cadastros e alterações exigem permissão específica.</div> : null}
    {section === "vehicles" ? <div className="siga-fleet-section"><div className="siga-fleet-section-head"><div><h2>Veículos</h2><p>Cadastros e situação operacional da frota demonstrativa.</p></div><label className="siga-fleet-search">Pesquisar <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Código, identificação, modelo" /></label></div>{canWrite ? <form className="siga-fleet-form" onSubmit={saveVehicle}><FormTitle title={editing === "vehicle" ? "Editar veículo" : "Novo veículo"} onClose={() => { setEditing(null); setVehicleForm(blankVehicle()); }} /><TextInput label="Código" value={vehicleForm.code} onChange={(value) => setVehicleForm({ ...vehicleForm, code: value })} required /><TextInput label="Patrimônio" value={vehicleForm.patrimony} onChange={(value) => setVehicleForm({ ...vehicleForm, patrimony: value })} required /><TextInput label="Identificação" value={vehicleForm.plate} onChange={(value) => setVehicleForm({ ...vehicleForm, plate: value })} required /><TextInput label="Modelo" value={vehicleForm.model} onChange={(value) => setVehicleForm({ ...vehicleForm, model: value })} required /><TextInput label="Categoria" value={vehicleForm.category} onChange={(value) => setVehicleForm({ ...vehicleForm, category: value })} required /><SelectInput label="Situação" value={vehicleForm.status} onChange={(value) => setVehicleForm({ ...vehicleForm, status: value as SemedFleetVehicle["status"] })} options={["Ativo", "Em manutenção", "Inativo"]} /><NumberInput label="Quilometragem" value={vehicleForm.odometerKm} onChange={(value) => setVehicleForm({ ...vehicleForm, odometerKm: value })} /><NumberInput label="Capacidade" value={vehicleForm.capacity} onChange={(value) => setVehicleForm({ ...vehicleForm, capacity: value })} /><TextInput label="Centro de custo" value={vehicleForm.costCenter} onChange={(value) => setVehicleForm({ ...vehicleForm, costCenter: value })} /><SaveButton /></form> : null}<div className="siga-fleet-list">{filteredVehicles.map((vehicle) => <article key={vehicle.id}><div><span className={`siga-fleet-status ${vehicle.status.replaceAll(" ", "-").toLocaleLowerCase()}`}>{vehicle.status}</span><h3>{vehicle.code} <small>{vehicle.plate}</small></h3><p>{vehicle.model} · {vehicle.category} · {vehicle.odometerKm.toLocaleString("pt-BR")} km</p></div>{canWrite ? <button type="button" onClick={() => { setVehicleForm(vehicle); setEditing("vehicle"); }}> <PenLine size={14} /> Editar</button> : null}</article>)}</div></div> : null}
    {section === "fuel" ? <div className="siga-fleet-section"><SectionHeading title="Controle de abastecimento" text="Registre litros, quilometragem, fornecedor e documento demonstrativo." />{canWrite ? <form className="siga-fleet-form" onSubmit={saveFuel}><FormTitle title={editing === "fuel" ? "Editar abastecimento" : "Novo abastecimento"} onClose={() => { setEditing(null); setFuelForm(blankFuel()); }} /><VehicleSelect vehicles={vehicles} value={fuelForm.vehicleId} onChange={(value) => setFuelForm({ ...fuelForm, vehicleId: value })} /><DateInput label="Data" value={fuelForm.fuelDate} onChange={(value) => setFuelForm({ ...fuelForm, fuelDate: value })} /><NumberInput label="Quilometragem" value={fuelForm.odometerKm} onChange={(value) => setFuelForm({ ...fuelForm, odometerKm: value })} /><NumberInput label="Litros" value={fuelForm.liters} onChange={(value) => setFuelForm({ ...fuelForm, liters: value })} step="0.01" /><NumberInput label="Valor unitário" value={fuelForm.unitPrice} onChange={(value) => setFuelForm({ ...fuelForm, unitPrice: value })} step="0.01" /><TextInput label="Fornecedor" value={fuelForm.supplier} onChange={(value) => setFuelForm({ ...fuelForm, supplier: value })} required /><TextInput label="Documento fiscal" value={fuelForm.documentReference} onChange={(value) => setFuelForm({ ...fuelForm, documentReference: value })} /><SelectInput label="Situação" value={fuelForm.status} onChange={(value) => setFuelForm({ ...fuelForm, status: value as SemedFleetFuel["status"] })} options={["Registrado", "Conferido", "Cancelado"]} /><SaveButton /></form> : null}<div className="siga-fleet-table">{fuelLogs.map((fuel) => <article key={fuel.id}><strong>{vehicleName(fuel.vehicleId)}</strong><span>{dateLabel(fuel.fuelDate)} · {fuel.liters} L · {money.format(fuel.totalAmount)}</span><em>{fuel.supplier} · {fuel.status}</em>{canWrite ? <button type="button" onClick={() => { setFuelForm(fuel); setEditing("fuel"); }}>Editar</button> : null}</article>)}</div></div> : null}
    {section === "maintenance" ? <div className="siga-fleet-section"><SectionHeading title="Controle de manutenção" text="Acompanhe manutenção preventiva e corretiva com próximos marcos." />{canWrite ? <form className="siga-fleet-form" onSubmit={saveMaintenance}><FormTitle title={editing === "maintenance" ? "Editar manutenção" : "Nova manutenção"} onClose={() => { setEditing(null); setMaintenanceForm(blankMaintenance()); }} /><VehicleSelect vehicles={vehicles} value={maintenanceForm.vehicleId} onChange={(value) => setMaintenanceForm({ ...maintenanceForm, vehicleId: value })} /><DateInput label="Data" value={maintenanceForm.maintenanceDate} onChange={(value) => setMaintenanceForm({ ...maintenanceForm, maintenanceDate: value })} /><NumberInput label="Quilometragem" value={maintenanceForm.odometerKm} onChange={(value) => setMaintenanceForm({ ...maintenanceForm, odometerKm: value })} /><SelectInput label="Tipo" value={maintenanceForm.type} onChange={(value) => setMaintenanceForm({ ...maintenanceForm, type: value as SemedFleetMaintenance["type"] })} options={["Preventiva", "Corretiva"]} /><TextInput label="Fornecedor" value={maintenanceForm.supplier} onChange={(value) => setMaintenanceForm({ ...maintenanceForm, supplier: value })} required /><NumberInput label="Custo" value={maintenanceForm.cost} onChange={(value) => setMaintenanceForm({ ...maintenanceForm, cost: value })} step="0.01" /><DateInput label="Próxima data" value={maintenanceForm.nextDate} onChange={(value) => setMaintenanceForm({ ...maintenanceForm, nextDate: value })} /><NumberInput label="Próxima quilometragem" value={maintenanceForm.nextOdometerKm} onChange={(value) => setMaintenanceForm({ ...maintenanceForm, nextOdometerKm: value })} /><SelectInput label="Situação" value={maintenanceForm.status} onChange={(value) => setMaintenanceForm({ ...maintenanceForm, status: value as SemedFleetMaintenance["status"] })} options={["Agendada", "Concluída", "Cancelada"]} /><TextInput label="Descrição" value={maintenanceForm.description} onChange={(value) => setMaintenanceForm({ ...maintenanceForm, description: value })} required /><SaveButton /></form> : null}<div className="siga-fleet-table">{maintenances.map((item) => <article key={item.id}><strong>{vehicleName(item.vehicleId)}</strong><span>{item.type} · {money.format(item.cost)} · próxima: {dateLabel(item.nextDate)}</span><em>{item.status} · {item.description}</em>{canWrite ? <button type="button" onClick={() => { setMaintenanceForm(item); setEditing("maintenance"); }}>Editar</button> : null}</article>)}</div></div> : null}
    {section === "occurrences" ? <div className="siga-fleet-section"><SectionHeading title="Controle de ocorrências" text="Registre, acompanhe e resolva ocorrências vinculadas a veículos." />{canWrite ? <form className="siga-fleet-form" onSubmit={saveOccurrence}><FormTitle title={editing === "occurrence" ? "Editar ocorrência" : "Nova ocorrência"} onClose={() => { setEditing(null); setOccurrenceForm(blankOccurrence()); }} /><VehicleSelect vehicles={vehicles} value={occurrenceForm.vehicleId} onChange={(value) => setOccurrenceForm({ ...occurrenceForm, vehicleId: value })} /><DateInput label="Data" value={occurrenceForm.occurrenceDate} onChange={(value) => setOccurrenceForm({ ...occurrenceForm, occurrenceDate: value })} /><SelectInput label="Tipo" value={occurrenceForm.type} onChange={(value) => setOccurrenceForm({ ...occurrenceForm, type: value as SemedFleetOccurrence["type"] })} options={["Acidente", "Avaria", "Infração", "Outro"]} /><SelectInput label="Situação" value={occurrenceForm.status} onChange={(value) => setOccurrenceForm({ ...occurrenceForm, status: value as SemedFleetOccurrence["status"] })} options={["Aberta", "Em apuração", "Resolvida"]} /><TextInput label="Local" value={occurrenceForm.location} onChange={(value) => setOccurrenceForm({ ...occurrenceForm, location: value })} required /><TextInput label="Descrição" value={occurrenceForm.description} onChange={(value) => setOccurrenceForm({ ...occurrenceForm, description: value })} required /><TextInput label="Resolução" value={occurrenceForm.resolution} onChange={(value) => setOccurrenceForm({ ...occurrenceForm, resolution: value })} /><SaveButton /></form> : null}<div className="siga-fleet-table">{occurrences.map((item) => <article key={item.id}><strong>{vehicleName(item.vehicleId)}</strong><span>{item.type} · {dateLabel(item.occurrenceDate)}</span><em>{item.status} · {item.description}</em>{canWrite ? <button type="button" onClick={() => { setOccurrenceForm(item); setEditing("occurrence"); }}>Editar</button> : null}</article>)}</div></div> : null}
    {section === "reports" ? <div className="siga-fleet-section"><div className="siga-fleet-report-head"><SectionHeading title="Relatórios de Frota" text="Consolidação local por veículo e situação, sem enviar ou consumir dados externos." /><div><button type="button" onClick={exportReport}><Download size={15} /> CSV local</button><button type="button" onClick={() => window.print()}><Printer size={15} /> Imprimir</button></div></div><div className="siga-fleet-report-grid">{vehicles.map((vehicle) => <article key={vehicle.id}><h3>{vehicle.code} <small>{vehicle.plate}</small></h3><span>{vehicle.status} · {vehicle.odometerKm.toLocaleString("pt-BR")} km</span><dl><div><dt>Abastecimentos</dt><dd>{fuelLogs.filter((item) => item.vehicleId === vehicle.id).length}</dd></div><div><dt>Manutenções</dt><dd>{maintenances.filter((item) => item.vehicleId === vehicle.id).length}</dd></div><div><dt>Ocorrências</dt><dd>{occurrences.filter((item) => item.vehicleId === vehicle.id).length}</dd></div></dl></article>)}</div></div> : null}
  </section>;
}

function Metric({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string | number; tone: string }) { return <article className={`siga-fleet-metric ${tone}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></article>; }
function SectionHeading({ title, text }: { title: string; text: string }) { return <div className="siga-fleet-section-heading"><h2>{title}</h2><p>{text}</p></div>; }
function FormTitle({ title, onClose }: { title: string; onClose: () => void }) { return <div className="siga-fleet-form-title"><strong>{title}</strong><button type="button" onClick={onClose}><X size={14} /> Limpar</button></div>; }
function TextInput({ label, value, onChange, required = false }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) { return <label>{label}<input value={value} onChange={(event) => onChange(event.target.value)} required={required} /></label>; }
function NumberInput({ label, value, onChange, step = "1" }: { label: string; value: number; onChange: (value: number) => void; step?: string }) { return <label>{label}<input type="number" min="0" step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} required /></label>; }
function DateInput({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label>{label}<input type="date" value={value} onChange={(event) => onChange(event.target.value)} required /></label>; }
function SelectInput({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((item) => <option key={item}>{item}</option>)}</select></label>; }
function VehicleSelect({ vehicles, value, onChange }: { vehicles: SemedFleetVehicle[]; value: string; onChange: (value: string) => void }) { return <label>Veículo<select value={value} onChange={(event) => onChange(event.target.value)} required><option value="" disabled>Selecione</option>{vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.code} · {vehicle.model}</option>)}</select></label>; }
function SaveButton() { return <button className="siga-fleet-save" type="submit"><Save size={15} /> Salvar localmente</button>; }
