import React, { FormEvent, useMemo, useState } from "react";
import { BadgeCheck, ClipboardList, FileText, Handshake, PackageCheck, Plus, ReceiptText, Tractor } from "lucide-react";
import type { SemedAfBilling, SemedAfBillingInput, SemedAfContract, SemedAfContractInput, SemedAfContractProduct, SemedAfContractProductInput, SemedAfEntity, SemedAfEntityInput, SemedAfGuide, SemedAfGuideInput, SemedAfGuideItem, SemedAfGuideItemInput, SemedAfSupplyPlan, SemedAfSupplyPlanInput, SemedSchoolUnit } from "./sigaLocalStore";
import "./siga-stock.css";

type AgricultureProps = {
  entities: SemedAfEntity[]; contracts: SemedAfContract[]; contractProducts: SemedAfContractProduct[]; plans: SemedAfSupplyPlan[]; guides: SemedAfGuide[]; guideItems: SemedAfGuideItem[]; billings: SemedAfBilling[]; schoolUnits: SemedSchoolUnit[]; canWrite: boolean; actorName: string;
  onSaveEntity: (input: SemedAfEntityInput) => { error: string | null; entity: SemedAfEntity | null };
  onSaveContract: (input: SemedAfContractInput) => { error: string | null; contract: SemedAfContract | null };
  onSaveProduct: (input: SemedAfContractProductInput) => { error: string | null; product: SemedAfContractProduct | null };
  onSavePlan: (input: SemedAfSupplyPlanInput) => { error: string | null; plan: SemedAfSupplyPlan | null };
  onSaveGuide: (input: SemedAfGuideInput) => { error: string | null; guide: SemedAfGuide | null };
  onSaveGuideItem: (input: SemedAfGuideItemInput) => { error: string | null; item: SemedAfGuideItem | null };
  onReceiveGuide: (guideId: string, receivedByName: string) => { error: string | null; guide: SemedAfGuide | null };
  onSaveBilling: (input: SemedAfBillingInput) => { error: string | null; billing: SemedAfBilling | null };
  onNotify: (message: string) => void;
};

type Tab = "entities" | "contracts" | "plans" | "guides" | "billings";
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const date = (value: string) => value ? new Date(`${value.slice(0, 10)}T12:00:00`).toLocaleDateString("pt-BR") : "—";
const unitInep = (unit: SemedSchoolUnit) => unit.inep || unit.code;

function ActionForm({ title, children, onCancel }: { title: string; children: React.ReactNode; onCancel: () => void }) { return <form className="siga-data-form siga-stock-form siga-af-form" onSubmit={(event) => event.preventDefault()}><div className="siga-form-heading"><h2>{title}</h2><span>Registro demonstrativo persistido somente neste navegador.</span></div>{children}<div className="siga-form-actions"><button type="button" className="siga-secondary-button" onClick={onCancel}>Cancelar</button></div></form>; }

export default function SemedAgricultureFamilyPage(props: AgricultureProps) {
  const [tab, setTab] = useState<Tab>("entities"); const [form, setForm] = useState<"" | "entity" | "contract" | "product" | "plan" | "guide" | "guideItem" | "billing">("");
  const productsByContract = useMemo(() => new Map(props.contracts.map((contract) => [contract.id, props.contractProducts.filter((product) => product.contractId === contract.id)])), [props.contractProducts, props.contracts]);
  const open = (next: typeof form) => setForm(next);
  const save = (result: { error: string | null }, success: string) => { if (result.error) props.onNotify(result.error); else { setForm(""); props.onNotify(success); } };
  const receivedGuides = props.guides.filter((guide) => guide.status === "Recebida" || guide.status === "Confirmada");
  const tabMeta: Record<Tab, { label: string; icon: typeof Tractor }> = { entities: { label: "Entidades", icon: Tractor }, contracts: { label: "Contratos", icon: Handshake }, plans: { label: "Planos", icon: ClipboardList }, guides: { label: "Guias e recebimentos", icon: PackageCheck }, billings: { label: "Faturamento", icon: ReceiptText } };
  const primary = tab === "entities" ? "Nova entidade" : tab === "contracts" ? "Novo contrato" : tab === "plans" ? "Novo plano" : tab === "guides" ? "Nova guia" : "Novo faturamento";

  return <section className="siga-stock-page siga-agriculture-page" aria-label="Agricultura Familiar"><header className="siga-stock-hero"><span className="siga-stock-icon"><Tractor size={20} /></span><div><small>Alimentação escolar</small><h1>Agricultura Familiar</h1><p>Entidades, contratos, planos, guias, recebimentos e faturamento com dados exclusivamente demonstrativos locais.</p></div><div className="siga-stock-hero-actions">{props.canWrite ? <button type="button" className="primary" onClick={() => open(tab === "entities" ? "entity" : tab === "contracts" ? "contract" : tab === "plans" ? "plan" : tab === "guides" ? "guide" : "billing")}><Plus size={16} />{primary}</button> : null}</div></header>
    <section className="siga-summary-grid siga-stock-metrics"><Metric label="Entidades ativas" value={props.entities.filter((entity) => entity.status === "Ativa").length} tone="good" /><Metric label="Contratos ativos" value={props.contracts.filter((contract) => contract.status === "Ativo").length} tone="neutral" /><Metric label="Guias recebidas" value={receivedGuides.length} tone="money" /><Metric label="Faturamentos" value={props.billings.length} tone="warning" /></section>
    <nav className="siga-module-tabs siga-stock-tabs" aria-label="Etapas de Agricultura Familiar">{(Object.keys(tabMeta) as Tab[]).map((key) => { const Icon = tabMeta[key].icon; return <button key={key} type="button" className={tab === key ? "active" : ""} onClick={() => { setTab(key); setForm(""); }}><Icon size={16} />{tabMeta[key].label}</button>; })}</nav>
    {!props.canWrite ? <p className="siga-workspace-notice">Perfil em modo somente leitura para Agricultura Familiar.</p> : null}
    <section className="siga-stock-workspace">{tab === "entities" ? <EntitiesPanel entities={props.entities} /> : null}{tab === "contracts" ? <ContractsPanel contracts={props.contracts} entities={props.entities} productsByContract={productsByContract} /> : null}{tab === "plans" ? <PlansPanel plans={props.plans} contracts={props.contracts} /> : null}{tab === "guides" ? <GuidesPanel guides={props.guides} guideItems={props.guideItems} contracts={props.contracts} onReceive={(guideId) => save(props.onReceiveGuide(guideId, props.actorName), "Recebimento local confirmado na guia.")} canWrite={props.canWrite} /> : null}{tab === "billings" ? <BillingsPanel billings={props.billings} guides={props.guides} contracts={props.contracts} /> : null}
      {form === "entity" ? <EntityForm onCancel={() => setForm("")} onSave={(input) => save(props.onSaveEntity(input), "Entidade fornecedora salva localmente.")} /> : null}
      {form === "contract" ? <ContractForm entities={props.entities} onCancel={() => setForm("")} onSave={(input) => save(props.onSaveContract(input), "Contrato local de Agricultura Familiar salvo.")} /> : null}
      {form === "product" ? <ProductForm contracts={props.contracts} onCancel={() => setForm("")} onSave={(input) => save(props.onSaveProduct(input), "Produto contratado registrado localmente.")} /> : null}
      {form === "plan" ? <PlanForm contracts={props.contracts} schoolUnits={props.schoolUnits} productsByContract={productsByContract} onCancel={() => setForm("")} onSave={(input) => save(props.onSavePlan(input), "Plano local de abastecimento salvo.")} /> : null}
      {form === "guide" ? <GuideForm contracts={props.contracts} schoolUnits={props.schoolUnits} onCancel={() => setForm("")} onSave={(input) => save(props.onSaveGuide(input), "Guia local de fornecimento salva.")} /> : null}
      {form === "guideItem" ? <GuideItemForm guides={props.guides} productsByContract={productsByContract} onCancel={() => setForm("")} onSave={(input) => save(props.onSaveGuideItem(input), "Item planejado da guia registrado.")} /> : null}
      {form === "billing" ? <BillingForm guides={receivedGuides} contracts={props.contracts} onCancel={() => setForm("")} onSave={(input) => save(props.onSaveBilling(input), "Faturamento demonstrativo local salvo.")} /> : null}
      {props.canWrite && tab === "contracts" ? <button type="button" className="siga-secondary-button siga-af-inline-action" onClick={() => open("product")}><Plus size={15} />Adicionar produto contratado</button> : null}{props.canWrite && tab === "guides" ? <button type="button" className="siga-secondary-button siga-af-inline-action" onClick={() => open("guideItem")}><Plus size={15} />Adicionar item à guia</button> : null}
    </section>
  </section>;
}

function Metric({ label, value, tone }: { label: string; value: number; tone: string }) { return <article className={`siga-metric-card ${tone}`}><span>{label}</span><strong>{value}</strong></article>; }
function EntitiesPanel({ entities }: { entities: SemedAfEntity[] }) { return <section className="siga-stock-table-panel"><div className="siga-list-heading"><div><p>Fornecedores</p><h2>Entidades da Agricultura Familiar</h2></div><span>{entities.length} registro(s)</span></div><div className="siga-stock-table-wrap"><table><thead><tr><th>Tipo</th><th>Entidade</th><th>Documento</th><th>Representante</th><th>Contato</th><th>Situação</th></tr></thead><tbody>{entities.map((entity) => <tr key={entity.id}><td>{entity.entityType}</td><td><strong>{entity.name}</strong><small>{entity.address || "Endereço não informado"}</small></td><td>{entity.document}</td><td>{entity.representative || "—"}</td><td>{entity.phone || entity.email || "—"}</td><td>{entity.status}</td></tr>)}</tbody></table>{!entities.length ? <p className="siga-stock-empty">Nenhuma entidade local cadastrada. Inicie pelo fornecedor demonstrativo.</p> : null}</div></section>; }
function ContractsPanel({ contracts, entities, productsByContract }: { contracts: SemedAfContract[]; entities: SemedAfEntity[]; productsByContract: Map<string, SemedAfContractProduct[]> }) { const entityName = (id: string) => entities.find((entity) => entity.id === id)?.name ?? "Entidade local"; return <section className="siga-stock-table-panel"><div className="siga-list-heading"><div><p>Contratação</p><h2>Contratos e itens contratados</h2></div><span>{contracts.length} contrato(s)</span></div><div className="siga-stock-table-wrap"><table><thead><tr><th>Contrato</th><th>Entidade</th><th>Processo</th><th>Vigência</th><th>Produtos</th><th>Situação</th></tr></thead><tbody>{contracts.map((contract) => <tr key={contract.id}><td><strong>{contract.number}</strong></td><td>{entityName(contract.entityId)}</td><td>{contract.processNumber || "—"}</td><td>{date(contract.startDate)} — {date(contract.endDate)}</td><td>{(productsByContract.get(contract.id) ?? []).map((product) => `${product.name} · ${product.contractedQuantity} ${product.unit}`).join("; ") || "Sem produtos"}</td><td>{contract.status}</td></tr>)}</tbody></table>{!contracts.length ? <p className="siga-stock-empty">Cadastre uma entidade antes de registrar contratos locais.</p> : null}</div></section>; }
function PlansPanel({ plans, contracts }: { plans: SemedAfSupplyPlan[]; contracts: SemedAfContract[] }) { return <section className="siga-stock-table-panel"><div className="siga-list-heading"><div><p>Planejamento</p><h2>Planos de abastecimento</h2></div><span>{plans.length} plano(s)</span></div><div className="siga-stock-table-wrap"><table><thead><tr><th>Mês</th><th>Unidade escolar</th><th>Contrato</th><th>Modalidade</th><th>Itens</th><th>Situação</th></tr></thead><tbody>{plans.map((plan) => <tr key={plan.id}><td>{plan.referenceMonth}</td><td>{plan.schoolName}</td><td>{contracts.find((contract) => contract.id === plan.contractId)?.number ?? "—"}</td><td>{plan.educationModality || "—"}</td><td>{plan.items.length}</td><td>{plan.status}</td></tr>)}</tbody></table>{!plans.length ? <p className="siga-stock-empty">Nenhum plano local registrado para a Agricultura Familiar.</p> : null}</div></section>; }
function GuidesPanel({ guides, guideItems, contracts, canWrite, onReceive }: { guides: SemedAfGuide[]; guideItems: SemedAfGuideItem[]; contracts: SemedAfContract[]; canWrite: boolean; onReceive: (guideId: string) => void }) { return <section className="siga-stock-table-panel"><div className="siga-list-heading"><div><p>Entrega e conferência</p><h2>Guias de fornecimento locais</h2></div><span>{guides.length} guia(s)</span></div><div className="siga-stock-table-wrap"><table><thead><tr><th>Guia</th><th>Contrato</th><th>Unidade</th><th>Entrega</th><th>Itens</th><th>Recebimento</th><th>Situação</th></tr></thead><tbody>{guides.map((guide) => <tr key={guide.id}><td><strong>{guide.guideNumber}</strong><small>{guide.deliveryMonth}</small></td><td>{contracts.find((contract) => contract.id === guide.contractId)?.number ?? "—"}</td><td>{guide.schoolName}</td><td>{date(guide.deliveryDate)}</td><td>{guideItems.filter((item) => item.guideId === guide.id).length}</td><td>{guide.receivedByName || "Pendente"}</td><td>{guide.status}{canWrite && guide.status === "Em elaboração" ? <button type="button" className="siga-table-action" onClick={() => onReceive(guide.id)}><BadgeCheck size={14} />Receber</button> : null}</td></tr>)}</tbody></table>{!guides.length ? <p className="siga-stock-empty">Nenhuma guia local criada. Registre a programação de entrega por unidade.</p> : null}</div></section>; }
function BillingsPanel({ billings, guides, contracts }: { billings: SemedAfBilling[]; guides: SemedAfGuide[]; contracts: SemedAfContract[] }) { return <section className="siga-stock-table-panel"><div className="siga-list-heading"><div><p>Faturamento</p><h2>Registros financeiros locais</h2></div><span>{billings.length} faturamento(s)</span></div><div className="siga-stock-table-wrap"><table><thead><tr><th>Faturamento</th><th>Guia</th><th>Contrato</th><th>Modalidade</th><th>Valor</th><th>Situação</th></tr></thead><tbody>{billings.map((billing) => <tr key={billing.id}><td>{billing.billingNumber}</td><td>{guides.find((guide) => guide.id === billing.guideId)?.guideNumber ?? "—"}</td><td>{contracts.find((contract) => contract.id === billing.contractId)?.number ?? "—"}</td><td>{billing.educationModality || "—"}</td><td>{money.format(billing.totalAmount)}</td><td>{billing.status}</td></tr>)}</tbody></table>{!billings.length ? <p className="siga-stock-empty">O faturamento local é liberado após o recebimento de uma guia.</p> : null}</div></section>; }
function EntityForm({ onCancel, onSave }: { onCancel: () => void; onSave: (input: SemedAfEntityInput) => void }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); onSave({ entityType: String(data.get("entityType")), name: String(data.get("name")), document: String(data.get("document")), representative: String(data.get("representative")), phone: String(data.get("phone")), email: String(data.get("email")), address: String(data.get("address")), status: String(data.get("status")) as SemedAfEntity["status"] }); }; return <form className="siga-data-form siga-stock-form siga-af-form" onSubmit={submit}><div className="siga-form-heading"><h2>Nova entidade fornecedora</h2><span>Associação, cooperativa ou fornecedor demonstrativo da Agricultura Familiar.</span></div><label>Tipo<select name="entityType"><option>Associação</option><option>Cooperativa</option><option>Fornecedor individual</option></select></label><label>Nome<input name="name" required placeholder="Nome da entidade" /></label><label>Documento<input name="document" required placeholder="CNPJ, CPF ou referência local" /></label><label>Representante<input name="representative" placeholder="Responsável local" /></label><label>Telefone<input name="phone" placeholder="(00) 00000-0000" /></label><label>E-mail<input name="email" type="email" placeholder="contato@exemplo.gov.br" /></label><label>Endereço<input name="address" placeholder="Endereço demonstrativo" /></label><label>Situação<select name="status"><option>Ativa</option><option>Inativa</option></select></label><div className="siga-form-actions"><button type="button" className="siga-secondary-button" onClick={onCancel}>Cancelar</button><button type="submit" className="siga-primary-button">Salvar entidade</button></div></form>; }
function ContractForm({ entities, onCancel, onSave }: { entities: SemedAfEntity[]; onCancel: () => void; onSave: (input: SemedAfContractInput) => void }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); onSave({ entityId: String(data.get("entityId")), number: String(data.get("number")), processNumber: String(data.get("processNumber")), startDate: String(data.get("startDate")), endDate: String(data.get("endDate")), status: String(data.get("status")) as SemedAfContract["status"], notes: String(data.get("notes")) }); }; return <form className="siga-data-form siga-stock-form siga-af-form" onSubmit={submit}><div className="siga-form-heading"><h2>Novo contrato local</h2><span>Vincule a entidade fornecedora e a vigência demonstrativa.</span></div><label>Entidade<select name="entityId" required><option value="">Selecionar entidade ativa</option>{entities.filter((entity) => entity.status === "Ativa").map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select></label><label>Número do contrato<input name="number" required placeholder="AF-2026-001" /></label><label>Processo administrativo<input name="processNumber" placeholder="PROC-LOCAL-001" /></label><label>Início da vigência<input name="startDate" type="date" /></label><label>Fim da vigência<input name="endDate" type="date" /></label><label>Situação<select name="status"><option>Ativo</option><option>Suspenso</option><option>Encerrado</option></select></label><label>Observações<textarea name="notes" rows={2} /></label><div className="siga-form-actions"><button type="button" className="siga-secondary-button" onClick={onCancel}>Cancelar</button><button type="submit" className="siga-primary-button">Salvar contrato</button></div></form>; }
function ProductForm({ contracts, onCancel, onSave }: { contracts: SemedAfContract[]; onCancel: () => void; onSave: (input: SemedAfContractProductInput) => void }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); onSave({ contractId: String(data.get("contractId")), name: String(data.get("name")), unit: String(data.get("unit")), contractedQuantity: Number(data.get("contractedQuantity")), unitPrice: Number(data.get("unitPrice")) }); }; return <form className="siga-data-form siga-stock-form siga-af-form" onSubmit={submit}><div className="siga-form-heading"><h2>Produto contratado</h2><span>Quantidade e preço demonstrativos vinculados ao contrato local.</span></div><label>Contrato<select name="contractId" required><option value="">Selecionar contrato</option>{contracts.filter((contract) => contract.status === "Ativo").map((contract) => <option key={contract.id} value={contract.id}>{contract.number}</option>)}</select></label><label>Produto<input name="name" required placeholder="Produto da Agricultura Familiar" /></label><label>Unidade<select name="unit"><option>KG</option><option>UN</option><option>L</option></select></label><label>Quantidade contratada<input name="contractedQuantity" type="number" min="0.001" step="0.001" required /></label><label>Preço unitário<input name="unitPrice" type="number" min="0" step="0.01" required /></label><div className="siga-form-actions"><button type="button" className="siga-secondary-button" onClick={onCancel}>Cancelar</button><button type="submit" className="siga-primary-button">Salvar produto</button></div></form>; }
function PlanForm({ contracts, schoolUnits, productsByContract, onCancel, onSave }: { contracts: SemedAfContract[]; schoolUnits: SemedSchoolUnit[]; productsByContract: Map<string, SemedAfContractProduct[]>; onCancel: () => void; onSave: (input: SemedAfSupplyPlanInput) => void }) { const [contractId, setContractId] = useState(""); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const selected = schoolUnits.find((unit) => unitInep(unit) === data.get("schoolInep")); const products = productsByContract.get(contractId) ?? []; onSave({ contractId, schoolInep: String(data.get("schoolInep")), schoolName: selected?.name ?? "", referenceMonth: String(data.get("referenceMonth")), educationModality: String(data.get("educationModality")), weekDates: String(data.get("weekDates")).split(",").map((value) => value.trim()).filter(Boolean), items: products.map((product) => ({ productId: product.id, productName: product.name, unit: product.unit, unitPrice: product.unitPrice, quantityPlanned: 0 })), status: String(data.get("status")) as SemedAfSupplyPlan["status"], notes: String(data.get("notes")) }); }; return <form className="siga-data-form siga-stock-form siga-af-form" onSubmit={submit}><div className="siga-form-heading"><h2>Plano de abastecimento</h2><span>Planejamento mensal local por unidade escolar e contrato.</span></div><label>Contrato<select value={contractId} onChange={(event) => setContractId(event.target.value)} required><option value="">Selecionar contrato</option>{contracts.filter((contract) => contract.status === "Ativo").map((contract) => <option key={contract.id} value={contract.id}>{contract.number}</option>)}</select></label><label>Unidade escolar<select name="schoolInep" required><option value="">Selecionar unidade</option>{schoolUnits.map((unit) => <option key={unit.id} value={unitInep(unit)}>{unit.name}</option>)}</select></label><label>Mês de referência<input name="referenceMonth" type="month" required /></label><label>Modalidade<input name="educationModality" placeholder="Ex.: Ensino Fundamental" /></label><label>Datas semanais<input name="weekDates" placeholder="AAAA-MM-DD, AAAA-MM-DD" /></label><label>Situação<select name="status"><option>Em elaboração</option><option>Confirmado</option><option>Cancelado</option></select></label><label>Observações<textarea name="notes" rows={2} /></label><div className="siga-form-actions"><button type="button" className="siga-secondary-button" onClick={onCancel}>Cancelar</button><button type="submit" className="siga-primary-button">Salvar plano</button></div></form>; }
function GuideForm({ contracts, schoolUnits, onCancel, onSave }: { contracts: SemedAfContract[]; schoolUnits: SemedSchoolUnit[]; onCancel: () => void; onSave: (input: SemedAfGuideInput) => void }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const selected = schoolUnits.find((unit) => unitInep(unit) === data.get("schoolInep")); onSave({ guideNumber: String(data.get("guideNumber")), contractId: String(data.get("contractId")), schoolInep: String(data.get("schoolInep")), schoolName: selected?.name ?? "", deliveryDate: String(data.get("deliveryDate")), deliveryMonth: String(data.get("deliveryMonth")), educationModality: String(data.get("educationModality")), weekDates: String(data.get("weekDates")).split(",").map((value) => value.trim()).filter(Boolean), weeklyReceipts: [], carrier: String(data.get("carrier")), notes: String(data.get("notes")), status: "Em elaboração", receivedByName: "", receivedByRole: "", receivedByDocument: "", receivedDate: "", confirmationNotes: "" }); }; return <form className="siga-data-form siga-stock-form siga-af-form" onSubmit={submit}><div className="siga-form-heading"><h2>Nova guia de fornecimento</h2><span>A numeração local é gerada quando o campo for deixado em branco.</span></div><label>Número da guia<input name="guideNumber" placeholder="Gerado localmente" /></label><label>Contrato<select name="contractId" required><option value="">Selecionar contrato</option>{contracts.filter((contract) => contract.status === "Ativo").map((contract) => <option key={contract.id} value={contract.id}>{contract.number}</option>)}</select></label><label>Unidade escolar<select name="schoolInep" required><option value="">Selecionar unidade</option>{schoolUnits.map((unit) => <option key={unit.id} value={unitInep(unit)}>{unit.name}</option>)}</select></label><label>Data da entrega<input name="deliveryDate" type="date" required /></label><label>Mês de entrega<input name="deliveryMonth" type="month" /></label><label>Modalidade<input name="educationModality" placeholder="Etapa ou modalidade" /></label><label>Transportador<input name="carrier" placeholder="Responsável demonstrativo" /></label><label>Datas semanais<input name="weekDates" placeholder="AAAA-MM-DD, AAAA-MM-DD" /></label><label>Observações<textarea name="notes" rows={2} /></label><div className="siga-form-actions"><button type="button" className="siga-secondary-button" onClick={onCancel}>Cancelar</button><button type="submit" className="siga-primary-button">Salvar guia</button></div></form>; }
function GuideItemForm({ guides, productsByContract, onCancel, onSave }: { guides: SemedAfGuide[]; productsByContract: Map<string, SemedAfContractProduct[]>; onCancel: () => void; onSave: (input: SemedAfGuideItemInput) => void }) { const [guideId, setGuideId] = useState(""); const guide = guides.find((item) => item.id === guideId); const products = guide ? productsByContract.get(guide.contractId) ?? [] : []; const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const product = products.find((item) => item.id === data.get("productId")); onSave({ guideId, productId: String(data.get("productId")), productName: product?.name ?? "", unit: product?.unit ?? "KG", unitPrice: product?.unitPrice ?? 0, quantityPlanned: Number(data.get("quantityPlanned")), quantityReceived: 0, weeklyQuantities: [], weeklyReceived: [] }); }; return <form className="siga-data-form siga-stock-form siga-af-form" onSubmit={submit}><div className="siga-form-heading"><h2>Item da guia</h2><span>Vincule o produto contratado à programação de entrega local.</span></div><label>Guia<select value={guideId} onChange={(event) => setGuideId(event.target.value)} required><option value="">Selecionar guia</option>{guides.map((item) => <option key={item.id} value={item.id}>{item.guideNumber}</option>)}</select></label><label>Produto contratado<select name="productId" required><option value="">Selecionar produto</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>Quantidade planejada<input name="quantityPlanned" type="number" min="0.001" step="0.001" required /></label><div className="siga-form-actions"><button type="button" className="siga-secondary-button" onClick={onCancel}>Cancelar</button><button type="submit" className="siga-primary-button">Salvar item</button></div></form>; }
function BillingForm({ guides, contracts, onCancel, onSave }: { guides: SemedAfGuide[]; contracts: SemedAfContract[]; onCancel: () => void; onSave: (input: SemedAfBillingInput) => void }) { const [guideId, setGuideId] = useState(""); const guide = guides.find((item) => item.id === guideId); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); onSave({ guideId, contractId: guide?.contractId ?? "", educationModality: String(data.get("educationModality")), totalAmount: Number(data.get("totalAmount")), status: String(data.get("status")) as SemedAfBilling["status"] }); }; return <form className="siga-data-form siga-stock-form siga-af-form" onSubmit={submit}><div className="siga-form-heading"><h2>Novo faturamento local</h2><span>Disponível para guias previamente recebidas na simulação.</span></div><label>Guia recebida<select value={guideId} onChange={(event) => setGuideId(event.target.value)} required><option value="">Selecionar guia recebida</option>{guides.map((item) => <option key={item.id} value={item.id}>{item.guideNumber} · {contracts.find((contract) => contract.id === item.contractId)?.number ?? "Contrato"}</option>)}</select></label><label>Modalidade<input name="educationModality" defaultValue={guide?.educationModality ?? ""} placeholder="Modalidade atendida" /></label><label>Valor total<input name="totalAmount" type="number" min="0" step="0.01" required /></label><label>Situação<select name="status"><option>Em elaboração</option><option>Emitido</option><option>Pago</option><option>Cancelado</option></select></label><div className="siga-form-actions"><button type="button" className="siga-secondary-button" onClick={onCancel}>Cancelar</button><button type="submit" className="siga-primary-button">Salvar faturamento</button></div></form>; }
