import React, { FormEvent, useMemo, useState } from "react";
import { BarChart3, Building2, CheckCircle2, ClipboardList, Download, FileText, MapPinned, Pencil, Plus, Search, UsersRound, X } from "lucide-react";
import type { SemedEducaNucleus, SemedEducaNucleusInput, SemedLocalAccessUser, SemedSchoolUnit, SemedSchoolUnitInput } from "./sigaLocalStore";
import "./siga-schools-educa.css";

export type SchoolsEducaSection = "schools" | "schools-reports" | "educa" | "educa-reports";

type Props = {
  initialSection: SchoolsEducaSection;
  currentUser: SemedLocalAccessUser;
  schoolUnits: SemedSchoolUnit[];
  educaNuclei: SemedEducaNucleus[];
  canWriteSchools: boolean;
  canWriteEduca: boolean;
  onSaveSchool: (input: SemedSchoolUnitInput) => { error: string | null };
  onSaveNucleus: (input: SemedEducaNucleusInput) => { error: string | null };
  onNotify: (message: string) => void;
};

const csv = (name: string, header: string[], rows: Array<Array<string | number>>) => {
  const content = [header, ...rows].map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(";")).join("\n");
  const url = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" }));
  const link = document.createElement("a"); link.href = url; link.download = `${name}.csv`; link.click(); URL.revokeObjectURL(url);
};

function Metric({ label, value, tone = "neutral" }: { label: string; value: string | number; tone?: string }) {
  return <article className={`siga-metric-card ${tone}`}><span>{label}</span><strong>{value}</strong></article>;
}

function SchoolForm({ initial, onCancel, onSave }: { initial?: SemedSchoolUnit; onCancel: () => void; onSave: (input: SemedSchoolUnitInput) => void }) {
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    onSave({ id: initial?.id, code: String(data.get("code") ?? ""), name: String(data.get("name") ?? ""), type: data.get("type") as SemedSchoolUnitInput["type"], status: data.get("status") as SemedSchoolUnitInput["status"], censusYear: Number(data.get("censusYear")), neighborhood: String(data.get("neighborhood") ?? ""), address: String(data.get("address") ?? ""), students: Number(data.get("students")), hasUex: data.get("hasUex") === "on", hasMap: data.get("hasMap") === "on" });
  }
  return <form className="siga-data-form schools-educa-form" onSubmit={submit}>
    <div className="siga-form-heading"><h2>{initial ? "Editar unidade" : "Nova unidade"}</h2><span>Cadastro demonstrativo local estruturado pelos filtros observados na referência.</span></div>
    <div className="siga-form-two"><label>Código<input name="code" required defaultValue={initial?.code} placeholder="UE-DEMO-004" /></label><label>Ano de censo<input name="censusYear" required type="number" min="2000" max="2100" defaultValue={initial?.censusYear ?? 2026} /></label></div>
    <label>Nome da unidade<input name="name" required defaultValue={initial?.name} placeholder="Unidade escolar demonstrativa" /></label>
    <div className="siga-form-two"><label>Tipo<select name="type" defaultValue={initial?.type ?? "Municipal"}><option>Municipal</option><option>Conveniada</option></select></label><label>Situação<select name="status" defaultValue={initial?.status ?? "Ativa"}><option>Ativa</option><option>Inativa</option></select></label></div>
    <div className="siga-form-two"><label>Bairro ou setor<input name="neighborhood" defaultValue={initial?.neighborhood} placeholder="Setor demonstrativo" /></label><label>Estudantes agregados<input name="students" type="number" min="0" defaultValue={initial?.students ?? 0} /></label></div>
    <label>Endereço demonstrativo<input name="address" defaultValue={initial?.address} placeholder="Sem dados reais" /></label>
    <div className="siga-checkbox-row"><label><input name="hasUex" type="checkbox" defaultChecked={initial?.hasUex} />Possui UEx</label><label><input name="hasMap" type="checkbox" defaultChecked={initial?.hasMap} />Mapa local disponível</label></div>
    <div className="siga-form-actions"><button type="button" className="siga-secondary-button" onClick={onCancel}>Cancelar</button><button type="submit" className="siga-primary-button">{initial ? "Atualizar unidade" : "Cadastrar unidade"}</button></div>
  </form>;
}

function NucleusForm({ initial, onCancel, onSave }: { initial?: SemedEducaNucleus; onCancel: () => void; onSave: (input: SemedEducaNucleusInput) => void }) {
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); const split = (key: string) => String(data.get(key) ?? "").split(",").map((item) => item.trim()).filter(Boolean);
    onSave({ id: initial?.id, code: String(data.get("code") ?? ""), name: String(data.get("name") ?? ""), classification: data.get("classification") as SemedEducaNucleusInput["classification"], status: data.get("status") as SemedEducaNucleusInput["status"], roomCount: Number(data.get("roomCount")), capacityPerShift: Number(data.get("capacityPerShift")), activities: split("activities"), sportModalities: split("sportModalities"), address: String(data.get("address") ?? ""), coordination: String(data.get("coordination") ?? ""), supervision: String(data.get("supervision") ?? ""), integratedNutrition: data.get("integratedNutrition") === "on" });
  }
  return <form className="siga-data-form schools-educa-form" onSubmit={submit}>
    <div className="siga-form-heading"><h2>{initial ? "Editar núcleo" : "Novo núcleo"}</h2><span>Cadastro demonstrativo local de núcleo, atividade, capacidade e acompanhamento.</span></div>
    <div className="siga-form-two"><label>Código<input name="code" required defaultValue={initial?.code} placeholder="EP-DEMO-003" /></label><label>Situação<select name="status" defaultValue={initial?.status ?? "Ativo"}><option>Ativo</option><option>Inativo</option></select></label></div>
    <label>Nome do núcleo<input name="name" required defaultValue={initial?.name} placeholder="Núcleo demonstrativo" /></label>
    <div className="siga-form-two"><label>Classificação<select name="classification" defaultValue={initial?.classification ?? "Pedagógico"}><option>Pedagógico</option><option>Esportivo</option><option>Pleno</option></select></label><label>Capacidade por turno<input name="capacityPerShift" type="number" min="0" defaultValue={initial?.capacityPerShift ?? 0} /></label></div>
    <div className="siga-form-two"><label>Salas<input name="roomCount" type="number" min="0" defaultValue={initial?.roomCount ?? 0} /></label><label>Endereço demonstrativo<input name="address" defaultValue={initial?.address} placeholder="Sem dados reais" /></label></div>
    <label>Atividades (separe por vírgulas)<input name="activities" defaultValue={initial?.activities.join(", ")} placeholder="Atividade demonstrativa" /></label>
    <label>Modalidades esportivas (separe por vírgulas)<input name="sportModalities" defaultValue={initial?.sportModalities.join(", ")} placeholder="Modalidade demonstrativa" /></label>
    <div className="siga-form-two"><label>Coordenação demonstrativa<input name="coordination" defaultValue={initial?.coordination} /></label><label>Supervisão demonstrativa<input name="supervision" defaultValue={initial?.supervision} /></label></div>
    <div className="siga-checkbox-row"><label><input name="integratedNutrition" type="checkbox" defaultChecked={initial?.integratedNutrition} />Atendimento integrado à Nutrição</label></div>
    <div className="siga-form-actions"><button type="button" className="siga-secondary-button" onClick={onCancel}>Cancelar</button><button type="submit" className="siga-primary-button">{initial ? "Atualizar núcleo" : "Cadastrar núcleo"}</button></div>
  </form>;
}

function ReportActions({ onExport }: { onExport: () => void }) { return <div className="schools-educa-report-actions"><button type="button" className="siga-secondary-button" onClick={onExport}><Download size={16} />Exportar CSV local</button><button type="button" className="siga-secondary-button" onClick={() => window.print()}><FileText size={16} />Imprimir visão</button></div>; }

export default function SemedSchoolsEducaPage({ initialSection, schoolUnits, educaNuclei, canWriteSchools, canWriteEduca, onSaveSchool, onSaveNucleus, onNotify }: Props) {
  const isSchools = initialSection.startsWith("schools"); const isReports = initialSection.endsWith("reports");
  const [query, setQuery] = useState(""); const [typeFilter, setTypeFilter] = useState("Todos"); const [statusFilter, setStatusFilter] = useState("Todos"); const [yearFilter, setYearFilter] = useState("Todos"); const [formOpen, setFormOpen] = useState(false); const [editingSchool, setEditingSchool] = useState<SemedSchoolUnit | undefined>(); const [editingNucleus, setEditingNucleus] = useState<SemedEducaNucleus | undefined>();
  const schoolYears = useMemo(() => Array.from(new Set(schoolUnits.map((unit) => String(unit.censusYear)))).sort().reverse(), [schoolUnits]);
  const filteredSchools = schoolUnits.filter((unit) => `${unit.code} ${unit.name} ${unit.neighborhood}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")) && (typeFilter === "Todos" || unit.type === typeFilter) && (statusFilter === "Todos" || unit.status === statusFilter) && (yearFilter === "Todos" || String(unit.censusYear) === yearFilter));
  const filteredNuclei = educaNuclei.filter((nucleus) => `${nucleus.code} ${nucleus.name} ${nucleus.address} ${nucleus.coordination}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")) && (typeFilter === "Todos" || nucleus.classification === typeFilter) && (statusFilter === "Todos" || nucleus.status === statusFilter));
  const resetForm = () => { setFormOpen(false); setEditingSchool(undefined); setEditingNucleus(undefined); };
  const saveSchool = (input: SemedSchoolUnitInput) => { const result = onSaveSchool(input); if (result.error) return onNotify(result.error); resetForm(); onNotify("Unidade escolar salva na simulação local."); };
  const saveNucleus = (input: SemedEducaNucleusInput) => { const result = onSaveNucleus(input); if (result.error) return onNotify(result.error); resetForm(); onNotify("Núcleo salvo na simulação local."); };

  if (isSchools) {
    const active = schoolUnits.filter((unit) => unit.status === "Ativa");
    return <section className="schools-educa-page"><header className="schools-educa-heading"><div><p className="siga-kicker">Unidades Escolares</p><h1>{isReports ? "Relatórios de Unidades Escolares" : "Cadastro de Unidades Escolares"}</h1><span>{isReports ? "Consultas, indicadores e exportações locais por categoria, situação e ano de censo." : "Cadastro, filtros e acompanhamento de unidades demonstrativas."}</span></div><Building2 size={30} aria-hidden="true" /></header>
      {isReports ? <><div className="siga-summary-grid"><Metric label="Unidades" value={schoolUnits.length} /><Metric label="Ativas" value={active.length} tone="good" /><Metric label="Com UEx" value={schoolUnits.filter((unit) => unit.hasUex).length} tone="warning" /><Metric label="Mapeadas" value={schoolUnits.filter((unit) => unit.hasMap).length} tone="money" /></div><section className="schools-educa-report-grid"><article><BarChart3 size={20} /><h2>Gestão por categoria</h2><p>Distribuição local por tipo de unidade, situação e ano de censo.</p></article><article><UsersRound size={20} /><h2>Visão de estudantes</h2><p>Indicadores agregados por unidade, sem dados individuais.</p></article><article><MapPinned size={20} /><h2>Mapa institucional</h2><p>Estrutura preparada para mapa local quando houver fonte autorizada.</p></article></section><ReportActions onExport={() => csv("unidades-escolares-local", ["código", "unidade", "tipo", "situação", "censo", "estudantes"], schoolUnits.map((unit) => [unit.code, unit.name, unit.type, unit.status, unit.censusYear, unit.students]))} /><SchoolFilters query={query} setQuery={setQuery} typeFilter={typeFilter} setTypeFilter={setTypeFilter} statusFilter={statusFilter} setStatusFilter={setStatusFilter} yearFilter={yearFilter} setYearFilter={setYearFilter} years={schoolYears} /><SchoolList units={filteredSchools} reportMode /></> : <><div className="siga-summary-grid"><Metric label="Unidades" value={schoolUnits.length} /><Metric label="Ativas" value={active.length} tone="good" /><Metric label="Municipais" value={schoolUnits.filter((unit) => unit.type === "Municipal").length} tone="neutral" /><Metric label="Ano atual" value={schoolYears[0] ?? "—"} tone="money" /></div><section className="schools-educa-toolbar"><button type="button" disabled={!canWriteSchools} className="siga-primary-button" onClick={() => { resetForm(); setFormOpen(true); }}><Plus size={16} />Nova unidade</button>{!canWriteSchools ? <span>Perfil em modo somente leitura neste módulo.</span> : null}</section>{formOpen ? <SchoolForm initial={editingSchool} onCancel={resetForm} onSave={saveSchool} /> : null}<SchoolFilters query={query} setQuery={setQuery} typeFilter={typeFilter} setTypeFilter={setTypeFilter} statusFilter={statusFilter} setStatusFilter={setStatusFilter} yearFilter={yearFilter} setYearFilter={setYearFilter} years={schoolYears} /><SchoolList units={filteredSchools} onEdit={canWriteSchools ? (unit) => { setEditingSchool(unit); setFormOpen(true); } : undefined} /></>}
    </section>;
  }
  const active = educaNuclei.filter((nucleus) => nucleus.status === "Ativo");
  return <section className="schools-educa-page"><header className="schools-educa-heading"><div><p className="siga-kicker">Educa Paço</p><h1>{isReports ? "Relatórios de Educa Paço" : "Cadastro de Núcleos"}</h1><span>{isReports ? "Indicadores e consultas locais por classificação, atividade e situação." : "Núcleos, capacidade, atividades e acompanhamento demonstrativos."}</span></div><UsersRound size={30} aria-hidden="true" /></header>
    {isReports ? <><div className="siga-summary-grid"><Metric label="Núcleos" value={educaNuclei.length} /><Metric label="Ativos" value={active.length} tone="good" /><Metric label="Capacidade" value={educaNuclei.reduce((total, nucleus) => total + nucleus.capacityPerShift, 0)} tone="money" /><Metric label="Com esporte" value={educaNuclei.filter((nucleus) => nucleus.sportModalities.length).length} tone="warning" /></div><section className="schools-educa-report-grid"><article><BarChart3 size={20} /><h2>Classificação e atividade</h2><p>Consulta local por núcleo, classificação, atividade e modalidade esportiva.</p></article><article><UsersRound size={20} /><h2>Capacidade por turno</h2><p>Leitura agregada de salas e capacidade demonstrativa.</p></article><article><ClipboardList size={20} /><h2>Equipe responsável</h2><p>Campos de coordenação e supervisão sem dados pessoais reais.</p></article></section><ReportActions onExport={() => csv("educa-paco-local", ["código", "núcleo", "classificação", "situação", "capacidade"], educaNuclei.map((nucleus) => [nucleus.code, nucleus.name, nucleus.classification, nucleus.status, nucleus.capacityPerShift]))} /><NucleusFilters query={query} setQuery={setQuery} typeFilter={typeFilter} setTypeFilter={setTypeFilter} statusFilter={statusFilter} setStatusFilter={setStatusFilter} /><NucleusList nuclei={filteredNuclei} reportMode /></> : <><div className="siga-summary-grid"><Metric label="Núcleos" value={educaNuclei.length} /><Metric label="Ativos" value={active.length} tone="good" /><Metric label="Atividades" value={educaNuclei.reduce((total, nucleus) => total + nucleus.activities.length, 0)} tone="neutral" /><Metric label="Capacidade" value={educaNuclei.reduce((total, nucleus) => total + nucleus.capacityPerShift, 0)} tone="money" /></div><section className="schools-educa-toolbar"><button type="button" disabled={!canWriteEduca} className="siga-primary-button" onClick={() => { resetForm(); setFormOpen(true); }}><Plus size={16} />Novo núcleo</button>{!canWriteEduca ? <span>Perfil em modo somente leitura neste módulo.</span> : null}</section>{formOpen ? <NucleusForm initial={editingNucleus} onCancel={resetForm} onSave={saveNucleus} /> : null}<NucleusFilters query={query} setQuery={setQuery} typeFilter={typeFilter} setTypeFilter={setTypeFilter} statusFilter={statusFilter} setStatusFilter={setStatusFilter} /><NucleusList nuclei={filteredNuclei} onEdit={canWriteEduca ? (nucleus) => { setEditingNucleus(nucleus); setFormOpen(true); } : undefined} /></>}
  </section>;
}

function SchoolFilters({ query, setQuery, typeFilter, setTypeFilter, statusFilter, setStatusFilter, yearFilter, setYearFilter, years }: { query: string; setQuery: (value: string) => void; typeFilter: string; setTypeFilter: (value: string) => void; statusFilter: string; setStatusFilter: (value: string) => void; yearFilter: string; setYearFilter: (value: string) => void; years: string[] }) { return <div className="siga-filters schools-educa-filters"><span><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Código, unidade ou setor..." /></span><select value={typeFilter} onChange={(event) => setTypeFilter(event.target.value)}><option>Todos</option><option>Municipal</option><option>Conveniada</option></select><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option>Todos</option><option>Ativa</option><option>Inativa</option></select><select value={yearFilter} onChange={(event) => setYearFilter(event.target.value)}><option>Todos</option>{years.map((year) => <option key={year}>{year}</option>)}</select></div>; }
function NucleusFilters({ query, setQuery, typeFilter, setTypeFilter, statusFilter, setStatusFilter }: { query: string; setQuery: (value: string) => void; typeFilter: string; setTypeFilter: (value: string) => void; statusFilter: string; setStatusFilter: (value: string) => void }) { return <div className="siga-filters schools-educa-filters"><span><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Código, núcleo, endereço ou responsável..." /></span><select value={typeFilter} onChange={(event) => setTypeFilter(event.target.value)}><option>Todos</option><option>Pedagógico</option><option>Esportivo</option><option>Pleno</option></select><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option>Todos</option><option>Ativo</option><option>Inativo</option></select></div>; }
function SchoolList({ units, onEdit, reportMode = false }: { units: SemedSchoolUnit[]; onEdit?: (unit: SemedSchoolUnit) => void; reportMode?: boolean }) { return <div className="schools-educa-list">{units.length ? units.map((unit) => <article key={unit.id} className="schools-educa-card"><div><small>{unit.code} · {unit.type}</small><h2>{unit.name}</h2><p>{unit.neighborhood || "Setor não informado"} · Censo {unit.censusYear}</p></div><div className="schools-educa-card-metrics"><span>{unit.students} estudantes</span><span className={unit.status === "Ativa" ? "good" : "muted"}>{unit.status}</span><span>{unit.hasUex ? "UEx" : "Sem UEx"}</span></div>{onEdit ? <button type="button" className="siga-icon-button" aria-label={`Editar ${unit.name}`} onClick={() => onEdit(unit)}><Pencil size={16} /></button> : reportMode ? <CheckCircle2 size={18} aria-label="Registro incluído no relatório" /> : null}</article>) : <p className="siga-empty-state">Nenhuma unidade encontrada para os filtros atuais.</p>}</div>; }
function NucleusList({ nuclei, onEdit, reportMode = false }: { nuclei: SemedEducaNucleus[]; onEdit?: (nucleus: SemedEducaNucleus) => void; reportMode?: boolean }) { return <div className="schools-educa-list">{nuclei.length ? nuclei.map((nucleus) => <article key={nucleus.id} className="schools-educa-card"><div><small>{nucleus.code} · {nucleus.classification}</small><h2>{nucleus.name}</h2><p>{nucleus.activities.join(" · ") || "Sem atividades informadas"}</p></div><div className="schools-educa-card-metrics"><span>{nucleus.capacityPerShift} vagas/turno</span><span className={nucleus.status === "Ativo" ? "good" : "muted"}>{nucleus.status}</span><span>{nucleus.sportModalities.length ? "Esporte" : "Geral"}</span></div>{onEdit ? <button type="button" className="siga-icon-button" aria-label={`Editar ${nucleus.name}`} onClick={() => onEdit(nucleus)}><Pencil size={16} /></button> : reportMode ? <CheckCircle2 size={18} aria-label="Registro incluído no relatório" /> : null}</article>) : <p className="siga-empty-state">Nenhum núcleo encontrado para os filtros atuais.</p>}</div>; }
