import React, { FormEvent, useMemo, useState } from "react";
import { BarChart3, Building2, CheckCircle2, ClipboardList, Download, FileText, MapPinned, Pencil, Plus, Search, UsersRound, X } from "lucide-react";
import type { SemedEducaNucleus, SemedEducaNucleusInput, SemedLocalAccessUser, SemedSchoolClass, SemedSchoolClassInput, SemedSchoolUnit, SemedSchoolUnitInput } from "./sigaLocalStore";
import "./siga-schools-educa.css";

export type SchoolsEducaSection = "schools" | "schools-reports" | "schools-classes" | "educa" | "educa-reports";

type Props = {
  initialSection: SchoolsEducaSection;
  currentUser: SemedLocalAccessUser;
  schoolUnits: SemedSchoolUnit[];
  schoolClasses?: SemedSchoolClass[];
  educaNuclei: SemedEducaNucleus[];
  canWriteSchools: boolean;
  canWriteEduca: boolean;
  onSaveSchool: (input: SemedSchoolUnitInput) => { error: string | null };
  onSaveSchoolClass?: (input: SemedSchoolClassInput) => { error: string | null };
  onSaveNucleus: (input: SemedEducaNucleusInput) => { error: string | null };
  onNotify: (message: string) => void;
};

const csv = (name: string, header: string[], rows: Array<Array<string | number>>) => {
  const content = [header, ...rows].map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(";")).join("\n");
  const url = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" }));
  const link = document.createElement("a"); link.href = url; link.download = `${name}.csv`; link.click(); URL.revokeObjectURL(url);
};

function Metric({ label, value, tone = "neutral" }: { label: string; value: string | number; tone?: string }) {
  return <article className={`siga-metric-card ${tone}`}><span>{label}</span><strong>{value}</strong></article>;
}

const SCHOOL_ENROLLMENT_FIELDS = [
  ["enrollmentCreche", "Matrículas — Creche"], ["enrollmentPreSchool", "Matrículas — Pré-escola"], ["enrollmentFundamental1", "Matrículas — Fundamental I"], ["enrollmentFundamental2", "Matrículas — Fundamental II"], ["enrollmentEjaiInitial", "Matrículas — EJA inicial"], ["enrollmentEjaiFinal", "Matrículas — EJA final"],
  ["enrollmentGrade1", "Matrículas — 1º ano"], ["enrollmentGrade2", "Matrículas — 2º ano"], ["enrollmentGrade3", "Matrículas — 3º ano"], ["enrollmentGrade4", "Matrículas — 4º ano"], ["enrollmentGrade5", "Matrículas — 5º ano"], ["enrollmentGrade6", "Matrículas — 6º ano"], ["enrollmentGrade7", "Matrículas — 7º ano"], ["enrollmentGrade8", "Matrículas — 8º ano"], ["enrollmentGrade9", "Matrículas — 9º ano"],
] as const;
const SCHOOL_SPECIAL_NEEDS_FIELDS = [
  ["specialNeedsCreche", "Necessidades especiais — Creche"], ["specialNeedsPreSchool", "Necessidades especiais — Pré-escola"], ["specialNeedsEjaiInitial", "Necessidades especiais — EJA inicial"], ["specialNeedsEjaiFinal", "Necessidades especiais — EJA final"],
  ["specialNeedsGrade1", "Necessidades especiais — 1º ano"], ["specialNeedsGrade2", "Necessidades especiais — 2º ano"], ["specialNeedsGrade3", "Necessidades especiais — 3º ano"], ["specialNeedsGrade4", "Necessidades especiais — 4º ano"], ["specialNeedsGrade5", "Necessidades especiais — 5º ano"], ["specialNeedsGrade6", "Necessidades especiais — 6º ano"], ["specialNeedsGrade7", "Necessidades especiais — 7º ano"], ["specialNeedsGrade8", "Necessidades especiais — 8º ano"], ["specialNeedsGrade9", "Necessidades especiais — 9º ano"],
] as const;
const SCHOOL_INFRASTRUCTURE_FIELDS = [["landAreaM2", "Área do terreno (m²)"], ["builtAreaM2", "Área construída (m²)"], ["classroomsTotal", "Salas totais"], ["classroomsInUse", "Salas em uso"], ["administrativeRooms", "Salas administrativas"], ["bathroomsTotal", "Banheiros"], ["accessibleBathrooms", "Banheiros acessíveis"]] as const;
const SCHOOL_NUMERIC_FIELDS = [...SCHOOL_ENROLLMENT_FIELDS, ...SCHOOL_SPECIAL_NEEDS_FIELDS, ...SCHOOL_INFRASTRUCTURE_FIELDS];
type SchoolNumericKey = (typeof SCHOOL_NUMERIC_FIELDS)[number][0];
const SCHOOL_TEXT_FIELDS = ["inep", "email", "managerName", "phone", "notes", "propertyType", "locationZone", "kitchenStatus", "cafeteriaStatus", "libraryStatus", "computerLabStatus", "sportsCourtStatus", "accessibilityStatus", "waterSupply", "energySupply", "sewageSystem", "internetAccess", "conservationStatus", "structureNotes"] as const;
type SchoolTextKey = (typeof SCHOOL_TEXT_FIELDS)[number];

function SchoolNumericGrid({ fields, initial }: { fields: ReadonlyArray<readonly [SchoolNumericKey, string]>; initial?: SemedSchoolUnit }) {
  return <div className="siga-form-four">{fields.map(([key, label]) => <label key={key}>{label}<input name={key} min="0" type="number" defaultValue={initial?.[key] ?? 0} /></label>)}</div>;
}

function SchoolForm({ initial, onCancel, onSave }: { initial?: SemedSchoolUnit; onCancel: () => void; onSave: (input: SemedSchoolUnitInput) => void }) {
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); const text = (key: string) => String(data.get(key) ?? "").trim(); const number = (key: string) => Number(data.get(key) ?? 0) || 0;
    const numericValues = Object.fromEntries(SCHOOL_NUMERIC_FIELDS.map(([key]) => [key, number(key)])) as Record<SchoolNumericKey, number>;
    const textValues = Object.fromEntries(SCHOOL_TEXT_FIELDS.map((key) => [key, text(key)])) as Record<SchoolTextKey, string>;
    onSave({ id: initial?.id, code: text("code"), name: text("name"), type: data.get("type") as SemedSchoolUnitInput["type"], status: data.get("status") as SemedSchoolUnitInput["status"], censusYear: number("censusYear"), neighborhood: text("neighborhood"), address: text("address"), students: number("students"), hasUex: data.get("hasUex") === "on", hasMap: data.get("hasMap") === "on", ...numericValues, ...textValues });
  }
  return <form className="siga-data-form schools-educa-form schools-educa-expanded-form" onSubmit={submit}>
    <div className="siga-form-heading"><h2>{initial ? "Editar unidade escolar" : "Nova unidade escolar"}</h2><span>Cadastro local com identificação, censo, matrículas, necessidades educacionais e infraestrutura.</span></div>
    <fieldset><legend>Identificação institucional</legend><div className="siga-form-two"><label>Código interno<input name="code" required defaultValue={initial?.code} placeholder="UE-DEMO-004" /></label><label>INEP<input name="inep" defaultValue={initial?.inep} placeholder="Código demonstrativo" /></label></div><label>Nome da unidade<input name="name" required defaultValue={initial?.name} placeholder="Unidade escolar demonstrativa" /></label><div className="siga-form-two"><label>E-mail institucional<input name="email" type="email" defaultValue={initial?.email} /></label><label>Telefone institucional<input name="phone" defaultValue={initial?.phone} /></label></div><div className="siga-form-two"><label>Gestor(a) responsável<input name="managerName" defaultValue={initial?.managerName} /></label><label>Ano do censo<input name="censusYear" required type="number" min="2000" max="2100" defaultValue={initial?.censusYear ?? 2026} /></label></div><div className="siga-form-two"><label>Tipo<select name="type" defaultValue={initial?.type ?? "Municipal"}><option>Municipal</option><option>Conveniada</option></select></label><label>Situação<select name="status" defaultValue={initial?.status ?? "Ativa"}><option>Ativa</option><option>Inativa</option></select></label></div><div className="siga-form-two"><label>Bairro ou setor<input name="neighborhood" defaultValue={initial?.neighborhood} /></label><label>Zona de localização<select name="locationZone" defaultValue={initial?.locationZone ?? ""}><option value="">Não informada</option><option>Urbana</option><option>Rural</option></select></label></div><label>Endereço demonstrativo<input name="address" defaultValue={initial?.address} /></label><label>Tipo de imóvel<input name="propertyType" defaultValue={initial?.propertyType} placeholder="Próprio, cedido ou alugado" /></label></fieldset>
    <fieldset><legend>Matrículas e atendimento educacional</legend><div className="siga-form-two"><label>Estudantes agregados<input name="students" type="number" min="0" defaultValue={initial?.students ?? 0} /></label><span className="siga-field-help">Preencha o detalhamento do censo conforme a disponibilidade local.</span></div><SchoolNumericGrid fields={SCHOOL_ENROLLMENT_FIELDS} initial={initial} /><h3>Estudantes com necessidades educacionais especiais</h3><SchoolNumericGrid fields={SCHOOL_SPECIAL_NEEDS_FIELDS} initial={initial} /></fieldset>
    <fieldset><legend>Infraestrutura e acessibilidade</legend><SchoolNumericGrid fields={SCHOOL_INFRASTRUCTURE_FIELDS} initial={initial} /><div className="siga-form-four"><label>Cozinha<select name="kitchenStatus" defaultValue={initial?.kitchenStatus ?? ""}><option value="">Não informada</option><option>Adequada</option><option>Parcial</option><option>Inadequada</option></select></label><label>Refeitório<select name="cafeteriaStatus" defaultValue={initial?.cafeteriaStatus ?? ""}><option value="">Não informado</option><option>Adequado</option><option>Parcial</option><option>Inadequado</option></select></label><label>Biblioteca<select name="libraryStatus" defaultValue={initial?.libraryStatus ?? ""}><option value="">Não informada</option><option>Disponível</option><option>Em implantação</option><option>Indisponível</option></select></label><label>Laboratório de informática<select name="computerLabStatus" defaultValue={initial?.computerLabStatus ?? ""}><option value="">Não informado</option><option>Disponível</option><option>Parcial</option><option>Indisponível</option></select></label><label>Quadra esportiva<select name="sportsCourtStatus" defaultValue={initial?.sportsCourtStatus ?? ""}><option value="">Não informada</option><option>Disponível</option><option>Parcial</option><option>Indisponível</option></select></label><label>Acessibilidade geral<select name="accessibilityStatus" defaultValue={initial?.accessibilityStatus ?? ""}><option value="">Não informada</option><option>Adequada</option><option>Parcial</option><option>Inadequada</option></select></label><label>Abastecimento de água<input name="waterSupply" defaultValue={initial?.waterSupply} /></label><label>Energia elétrica<input name="energySupply" defaultValue={initial?.energySupply} /></label><label>Esgotamento sanitário<input name="sewageSystem" defaultValue={initial?.sewageSystem} /></label><label>Acesso à internet<input name="internetAccess" defaultValue={initial?.internetAccess} /></label><label>Conservação<select name="conservationStatus" defaultValue={initial?.conservationStatus ?? ""}><option value="">Não informada</option><option>Boa</option><option>Regular</option><option>Crítica</option></select></label></div><label>Observações de estrutura<textarea name="structureNotes" rows={3} defaultValue={initial?.structureNotes} /></label></fieldset>
    <fieldset><legend>Referências complementares</legend><div className="siga-checkbox-row"><label><input name="hasUex" type="checkbox" defaultChecked={initial?.hasUex} />Possui UEx</label><label><input name="hasMap" type="checkbox" defaultChecked={initial?.hasMap} />Mapa local disponível</label></div><label>Observações gerais<textarea name="notes" rows={3} defaultValue={initial?.notes} /></label></fieldset>
    <div className="siga-form-actions"><button type="button" className="siga-secondary-button" onClick={onCancel}>Cancelar</button><button type="submit" className="siga-primary-button">{initial ? "Atualizar unidade" : "Cadastrar unidade"}</button></div>
  </form>;
}

function SchoolClassForm({ initial, units, onCancel, onSave }: { initial?: SemedSchoolClass; units: SemedSchoolUnit[]; onCancel: () => void; onSave: (input: SemedSchoolClassInput) => void }) {
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); const unitInep = String(data.get("unitInep") ?? ""); const unit = units.find((item) => (item.inep || item.code) === unitInep);
    onSave({ id: initial?.id, unitInep, schoolYear: Number(data.get("schoolYear") ?? 0), schoolName: unit?.name ?? "", className: String(data.get("className") ?? ""), classType: String(data.get("classType") ?? ""), students: Number(data.get("students") ?? 0), professionals: Number(data.get("professionals") ?? 0), sourceRow: String(data.get("sourceRow") ?? ""), source: String(data.get("source") ?? ""), importedAt: String(data.get("importedAt") ?? "") });
  }
  return <form className="siga-data-form schools-educa-form" onSubmit={submit}><div className="siga-form-heading"><h2>{initial ? "Editar turma" : "Nova turma"}</h2><span>Registro local vinculado ao INEP da unidade, ano letivo e quantitativos de estudantes e profissionais.</span></div><label>Unidade escolar<select name="unitInep" required defaultValue={initial?.unitInep ?? ""}><option value="" disabled>Selecione a unidade</option>{units.map((unit) => <option key={unit.id} value={unit.inep || unit.code}>{unit.name} · {unit.inep || unit.code}</option>)}</select></label><div className="siga-form-two"><label>Ano letivo<input name="schoolYear" type="number" min="2000" max="2100" defaultValue={initial?.schoolYear ?? 2026} /></label><label>Nome da turma<input name="className" required defaultValue={initial?.className} placeholder="Ex.: 4º ano A" /></label></div><div className="siga-form-two"><label>Etapa ou tipo<input name="classType" defaultValue={initial?.classType} placeholder="Ex.: Ensino Fundamental" /></label><label>Estudantes<input name="students" type="number" min="0" defaultValue={initial?.students ?? 0} /></label></div><div className="siga-form-two"><label>Profissionais<input name="professionals" type="number" min="0" defaultValue={initial?.professionals ?? 0} /></label><label>Linha de origem<input name="sourceRow" defaultValue={initial?.sourceRow} placeholder="Registro local" /></label></div><div className="siga-form-two"><label>Fonte do dado<input name="source" defaultValue={initial?.source ?? "Cadastro local"} /></label><label>Data de referência<input name="importedAt" type="date" defaultValue={initial?.importedAt} /></label></div><div className="siga-form-actions"><button type="button" className="siga-secondary-button" onClick={onCancel}>Cancelar</button><button type="submit" className="siga-primary-button">{initial ? "Atualizar turma" : "Cadastrar turma"}</button></div></form>;
}

function NucleusForm({ initial, onCancel, onSave }: { initial?: SemedEducaNucleus; onCancel: () => void; onSave: (input: SemedEducaNucleusInput) => void }) {
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); const split = (key: string) => String(data.get(key) ?? "").split(",").map((item) => item.trim()).filter(Boolean);
    onSave({ id: initial?.id, code: String(data.get("code") ?? ""), name: String(data.get("name") ?? ""), classification: data.get("classification") as SemedEducaNucleusInput["classification"], status: data.get("status") as SemedEducaNucleusInput["status"], roomCount: Number(data.get("roomCount")), capacityPerShift: Number(data.get("capacityPerShift")), activities: split("activities"), sportModalities: split("sportModalities"), address: String(data.get("address") ?? ""), coordination: String(data.get("coordination") ?? ""), supervision: String(data.get("supervision") ?? ""), integratedNutrition: data.get("integratedNutrition") === "on" });
  }
  return <form className="siga-data-form schools-educa-form" onSubmit={submit}>
    <div className="siga-form-heading"><h2>{initial ? "Editar núcleo" : "Novo núcleo"}</h2><span>Cadastro demonstrativo local de núcleo, atividade, capacidade e acompanhamento.</span></div>
    <div className="siga-form-two"><label>Código<input name="code" required defaultValue={initial?.code} placeholder="EP-DEMO-003" /></label><label>Situação<select name="status" defaultValue={initial?.status ?? "Ativo"}><option>Ativo</option><option>Inativo</option></select></label></div>
    <label>Nome do núcleo<input name="name" required defaultValue={initial?.name} placeholder="Núcleo demonstrativo" /></label>
    <div className="siga-form-two"><label>Classificação<select name="classification" defaultValue={initial?.classification ?? "Pedagógico"}><option>Pedagógico</option><option>Esportivo</option><option>Pleno</option></select></label><label>Capacidade por turno<input name="capacityPerShift" type="number" min="0" defaultValue={initial?.capacityPerShift ?? 0} /></label></div>
    <div className="siga-form-two"><label>Salas<input name="roomCount" type="number" min="0" defaultValue={initial?.roomCount ?? 0} /></label><label>Endereço demonstrativo<input name="address" defaultValue={initial?.address} placeholder="Sem dados reais" /></label></div>
    <label>Atividades (separe por vírgulas)<input name="activities" defaultValue={initial?.activities.join(", ")} placeholder="Atividade demonstrativa" /></label>
    <label>Modalidades esportivas (separe por vírgulas)<input name="sportModalities" defaultValue={initial?.sportModalities.join(", ")} placeholder="Modalidade demonstrativa" /></label>
    <div className="siga-form-two"><label>Coordenação demonstrativa<input name="coordination" defaultValue={initial?.coordination} /></label><label>Supervisão demonstrativa<input name="supervision" defaultValue={initial?.supervision} /></label></div>
    <div className="siga-checkbox-row"><label><input name="integratedNutrition" type="checkbox" defaultChecked={initial?.integratedNutrition} />Atendimento integrado à Nutrição</label></div>
    <div className="siga-form-actions"><button type="button" className="siga-secondary-button" onClick={onCancel}>Cancelar</button><button type="submit" className="siga-primary-button">{initial ? "Atualizar núcleo" : "Cadastrar núcleo"}</button></div>
  </form>;
}

function ReportActions({ onExport }: { onExport: () => void }) { return <div className="schools-educa-report-actions"><button type="button" className="siga-secondary-button" onClick={onExport}><Download size={16} />Exportar CSV local</button><button type="button" className="siga-secondary-button" onClick={() => window.print()}><FileText size={16} />Imprimir visão</button></div>; }

export default function SemedSchoolsEducaPage({ initialSection, schoolUnits, schoolClasses = [], educaNuclei, canWriteSchools, canWriteEduca, onSaveSchool, onSaveSchoolClass = () => ({ error: "Turmas ainda não conectadas ao repositório local." }), onSaveNucleus, onNotify }: Props) {
  const isSchools = initialSection.startsWith("schools"); const isReports = initialSection.endsWith("reports"); const isClasses = initialSection === "schools-classes";
  const [query, setQuery] = useState(""); const [typeFilter, setTypeFilter] = useState("Todos"); const [statusFilter, setStatusFilter] = useState("Todos"); const [yearFilter, setYearFilter] = useState("Todos"); const [formOpen, setFormOpen] = useState(false); const [editingSchool, setEditingSchool] = useState<SemedSchoolUnit | undefined>(); const [editingClass, setEditingClass] = useState<SemedSchoolClass | undefined>(); const [editingNucleus, setEditingNucleus] = useState<SemedEducaNucleus | undefined>();
  const schoolYears = useMemo(() => Array.from(new Set(schoolUnits.map((unit) => String(unit.censusYear)))).sort().reverse(), [schoolUnits]);
  const filteredSchools = schoolUnits.filter((unit) => `${unit.code} ${unit.name} ${unit.neighborhood}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")) && (typeFilter === "Todos" || unit.type === typeFilter) && (statusFilter === "Todos" || unit.status === statusFilter) && (yearFilter === "Todos" || String(unit.censusYear) === yearFilter));
  const filteredClasses = schoolClasses.filter((schoolClass) => `${schoolClass.unitInep} ${schoolClass.schoolName} ${schoolClass.className} ${schoolClass.classType}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")) && (yearFilter === "Todos" || String(schoolClass.schoolYear) === yearFilter));
  const filteredNuclei = educaNuclei.filter((nucleus) => `${nucleus.code} ${nucleus.name} ${nucleus.address} ${nucleus.coordination}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")) && (typeFilter === "Todos" || nucleus.classification === typeFilter) && (statusFilter === "Todos" || nucleus.status === statusFilter));
  const resetForm = () => { setFormOpen(false); setEditingSchool(undefined); setEditingClass(undefined); setEditingNucleus(undefined); };
  const saveSchool = (input: SemedSchoolUnitInput) => { const result = onSaveSchool(input); if (result.error) return onNotify(result.error); resetForm(); onNotify("Unidade escolar salva na simulação local."); };
  const saveSchoolClass = (input: SemedSchoolClassInput) => { const result = onSaveSchoolClass(input); if (result.error) return onNotify(result.error); resetForm(); onNotify("Turma salva na simulação local."); };
  const saveNucleus = (input: SemedEducaNucleusInput) => { const result = onSaveNucleus(input); if (result.error) return onNotify(result.error); resetForm(); onNotify("Núcleo salvo na simulação local."); };

  if (isClasses) return <section className="schools-educa-page"><header className="schools-educa-heading"><div><p className="siga-kicker">Unidades Escolares</p><h1>Turmas e quantitativos</h1><span>Cadastro local de turmas vinculado à unidade, ano letivo, estudantes e profissionais.</span></div><UsersRound size={30} aria-hidden="true" /></header><div className="siga-summary-grid"><Metric label="Turmas" value={schoolClasses.length} /><Metric label="Estudantes" value={schoolClasses.reduce((total, schoolClass) => total + schoolClass.students, 0)} tone="good" /><Metric label="Profissionais" value={schoolClasses.reduce((total, schoolClass) => total + schoolClass.professionals, 0)} tone="money" /></div><section className="schools-educa-toolbar"><button type="button" disabled={!canWriteSchools} className="siga-primary-button" onClick={() => { resetForm(); setFormOpen(true); }}><Plus size={16} />Nova turma</button>{!canWriteSchools ? <span>Perfil em modo somente leitura neste módulo.</span> : null}</section>{formOpen ? <SchoolClassForm initial={editingClass} units={schoolUnits} onCancel={resetForm} onSave={saveSchoolClass} /> : null}<div className="siga-filters schools-educa-filters schools-classes-filter"><span><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Unidade, turma ou etapa..." /></span><select value={yearFilter} onChange={(event) => setYearFilter(event.target.value)}><option>Todos</option>{schoolYears.map((year) => <option key={year}>{year}</option>)}</select></div><SchoolClassList classes={filteredClasses} onEdit={canWriteSchools ? (schoolClass) => { setEditingClass(schoolClass); setFormOpen(true); } : undefined} /></section>;

  if (isSchools) {
    const active = schoolUnits.filter((unit) => unit.status === "Ativa");
    return <section className="schools-educa-page"><header className="schools-educa-heading"><div><p className="siga-kicker">Unidades Escolares</p><h1>{isReports ? "Relatórios de Unidades Escolares" : "Cadastro de Unidades Escolares"}</h1><span>{isReports ? "Consultas, indicadores e exportações locais por categoria, situação e ano de censo." : "Cadastro, filtros e acompanhamento de unidades demonstrativas."}</span></div><Building2 size={30} aria-hidden="true" /></header>
      {isReports ? <><div className="siga-summary-grid"><Metric label="Unidades" value={schoolUnits.length} /><Metric label="Ativas" value={active.length} tone="good" /><Metric label="Com UEx" value={schoolUnits.filter((unit) => unit.hasUex).length} tone="warning" /><Metric label="Mapeadas" value={schoolUnits.filter((unit) => unit.hasMap).length} tone="money" /></div><section className="schools-educa-report-grid"><article><BarChart3 size={20} /><h2>Gestão por categoria</h2><p>Distribuição local por tipo de unidade, situação e ano de censo.</p></article><article><UsersRound size={20} /><h2>Visão de estudantes</h2><p>Indicadores agregados por unidade, sem dados individuais.</p></article><article><MapPinned size={20} /><h2>Mapa institucional</h2><p>Estrutura preparada para mapa local quando houver fonte autorizada.</p></article></section><ReportActions onExport={() => csv("unidades-escolares-local", ["código", "unidade", "tipo", "situação", "censo", "estudantes"], schoolUnits.map((unit) => [unit.code, unit.name, unit.type, unit.status, unit.censusYear, unit.students]))} /><SchoolFilters query={query} setQuery={setQuery} typeFilter={typeFilter} setTypeFilter={setTypeFilter} statusFilter={statusFilter} setStatusFilter={setStatusFilter} yearFilter={yearFilter} setYearFilter={setYearFilter} years={schoolYears} /><SchoolList units={filteredSchools} reportMode /></> : <><div className="siga-summary-grid"><Metric label="Unidades" value={schoolUnits.length} /><Metric label="Ativas" value={active.length} tone="good" /><Metric label="Municipais" value={schoolUnits.filter((unit) => unit.type === "Municipal").length} tone="neutral" /><Metric label="Ano atual" value={schoolYears[0] ?? "—"} tone="money" /></div><section className="schools-educa-toolbar"><button type="button" disabled={!canWriteSchools} className="siga-primary-button" onClick={() => { resetForm(); setFormOpen(true); }}><Plus size={16} />Nova unidade</button>{!canWriteSchools ? <span>Perfil em modo somente leitura neste módulo.</span> : null}</section>{formOpen ? <SchoolForm initial={editingSchool} onCancel={resetForm} onSave={saveSchool} /> : null}<SchoolFilters query={query} setQuery={setQuery} typeFilter={typeFilter} setTypeFilter={setTypeFilter} statusFilter={statusFilter} setStatusFilter={setStatusFilter} yearFilter={yearFilter} setYearFilter={setYearFilter} years={schoolYears} /><SchoolList units={filteredSchools} onEdit={canWriteSchools ? (unit) => { setEditingSchool(unit); setFormOpen(true); } : undefined} /></>}
    </section>;
  }
  const active = educaNuclei.filter((nucleus) => nucleus.status === "Ativo");
  return <section className="schools-educa-page"><header className="schools-educa-heading"><div><p className="siga-kicker">Educa Paço</p><h1>{isReports ? "Relatórios de Educa Paço" : "Cadastro de Núcleos"}</h1><span>{isReports ? "Indicadores e consultas locais por classificação, atividade e situação." : "Núcleos, capacidade, atividades e acompanhamento demonstrativos."}</span></div><UsersRound size={30} aria-hidden="true" /></header>
    {isReports ? <><div className="siga-summary-grid"><Metric label="Núcleos" value={educaNuclei.length} /><Metric label="Ativos" value={active.length} tone="good" /><Metric label="Capacidade" value={educaNuclei.reduce((total, nucleus) => total + nucleus.capacityPerShift, 0)} tone="money" /><Metric label="Com esporte" value={educaNuclei.filter((nucleus) => nucleus.sportModalities.length).length} tone="warning" /></div><section className="schools-educa-report-grid"><article><BarChart3 size={20} /><h2>Classificação e atividade</h2><p>Consulta local por núcleo, classificação, atividade e modalidade esportiva.</p></article><article><UsersRound size={20} /><h2>Capacidade por turno</h2><p>Leitura agregada de salas e capacidade demonstrativa.</p></article><article><ClipboardList size={20} /><h2>Equipe responsável</h2><p>Campos de coordenação e supervisão sem dados pessoais reais.</p></article></section><ReportActions onExport={() => csv("educa-paco-local", ["código", "núcleo", "classificação", "situação", "capacidade"], educaNuclei.map((nucleus) => [nucleus.code, nucleus.name, nucleus.classification, nucleus.status, nucleus.capacityPerShift]))} /><NucleusFilters query={query} setQuery={setQuery} typeFilter={typeFilter} setTypeFilter={setTypeFilter} statusFilter={statusFilter} setStatusFilter={setStatusFilter} /><NucleusList nuclei={filteredNuclei} reportMode /></> : <><div className="siga-summary-grid"><Metric label="Núcleos" value={educaNuclei.length} /><Metric label="Ativos" value={active.length} tone="good" /><Metric label="Atividades" value={educaNuclei.reduce((total, nucleus) => total + nucleus.activities.length, 0)} tone="neutral" /><Metric label="Capacidade" value={educaNuclei.reduce((total, nucleus) => total + nucleus.capacityPerShift, 0)} tone="money" /></div><section className="schools-educa-toolbar"><button type="button" disabled={!canWriteEduca} className="siga-primary-button" onClick={() => { resetForm(); setFormOpen(true); }}><Plus size={16} />Novo núcleo</button>{!canWriteEduca ? <span>Perfil em modo somente leitura neste módulo.</span> : null}</section>{formOpen ? <NucleusForm initial={editingNucleus} onCancel={resetForm} onSave={saveNucleus} /> : null}<NucleusFilters query={query} setQuery={setQuery} typeFilter={typeFilter} setTypeFilter={setTypeFilter} statusFilter={statusFilter} setStatusFilter={setStatusFilter} /><NucleusList nuclei={filteredNuclei} onEdit={canWriteEduca ? (nucleus) => { setEditingNucleus(nucleus); setFormOpen(true); } : undefined} /></>}
  </section>;
}

function SchoolFilters({ query, setQuery, typeFilter, setTypeFilter, statusFilter, setStatusFilter, yearFilter, setYearFilter, years }: { query: string; setQuery: (value: string) => void; typeFilter: string; setTypeFilter: (value: string) => void; statusFilter: string; setStatusFilter: (value: string) => void; yearFilter: string; setYearFilter: (value: string) => void; years: string[] }) { return <div className="siga-filters schools-educa-filters"><span><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Código, unidade ou setor..." /></span><select value={typeFilter} onChange={(event) => setTypeFilter(event.target.value)}><option>Todos</option><option>Municipal</option><option>Conveniada</option></select><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option>Todos</option><option>Ativa</option><option>Inativa</option></select><select value={yearFilter} onChange={(event) => setYearFilter(event.target.value)}><option>Todos</option>{years.map((year) => <option key={year}>{year}</option>)}</select></div>; }
function NucleusFilters({ query, setQuery, typeFilter, setTypeFilter, statusFilter, setStatusFilter }: { query: string; setQuery: (value: string) => void; typeFilter: string; setTypeFilter: (value: string) => void; statusFilter: string; setStatusFilter: (value: string) => void }) { return <div className="siga-filters schools-educa-filters"><span><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Código, núcleo, endereço ou responsável..." /></span><select value={typeFilter} onChange={(event) => setTypeFilter(event.target.value)}><option>Todos</option><option>Pedagógico</option><option>Esportivo</option><option>Pleno</option></select><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option>Todos</option><option>Ativo</option><option>Inativo</option></select></div>; }
function SchoolList({ units, onEdit, reportMode = false }: { units: SemedSchoolUnit[]; onEdit?: (unit: SemedSchoolUnit) => void; reportMode?: boolean }) { return <div className="schools-educa-list">{units.length ? units.map((unit) => <article key={unit.id} className="schools-educa-card"><div><small>{unit.code} · {unit.type}</small><h2>{unit.name}</h2><p>{unit.neighborhood || "Setor não informado"} · Censo {unit.censusYear}</p></div><div className="schools-educa-card-metrics"><span>{unit.students} estudantes</span><span className={unit.status === "Ativa" ? "good" : "muted"}>{unit.status}</span><span>{unit.hasUex ? "UEx" : "Sem UEx"}</span></div>{onEdit ? <button type="button" className="siga-icon-button" aria-label={`Editar ${unit.name}`} onClick={() => onEdit(unit)}><Pencil size={16} /></button> : reportMode ? <CheckCircle2 size={18} aria-label="Registro incluído no relatório" /> : null}</article>) : <p className="siga-empty-state">Nenhuma unidade encontrada para os filtros atuais.</p>}</div>; }
function SchoolClassList({ classes, onEdit }: { classes: SemedSchoolClass[]; onEdit?: (schoolClass: SemedSchoolClass) => void }) { return <div className="schools-educa-list">{classes.length ? classes.map((schoolClass) => <article key={schoolClass.id} className="schools-educa-card"><div><small>{schoolClass.unitInep} · {schoolClass.schoolYear}</small><h2>{schoolClass.className}</h2><p>{schoolClass.schoolName} · {schoolClass.classType || "Etapa não informada"}</p></div><div className="schools-educa-card-metrics"><span>{schoolClass.students} estudantes</span><span>{schoolClass.professionals} profissionais</span></div>{onEdit ? <button type="button" className="siga-icon-button" aria-label={`Editar ${schoolClass.className}`} onClick={() => onEdit(schoolClass)}><Pencil size={16} /></button> : null}</article>) : <p className="siga-empty-state">Nenhuma turma cadastrada localmente.</p>}</div>; }
function NucleusList({ nuclei, onEdit, reportMode = false }: { nuclei: SemedEducaNucleus[]; onEdit?: (nucleus: SemedEducaNucleus) => void; reportMode?: boolean }) { return <div className="schools-educa-list">{nuclei.length ? nuclei.map((nucleus) => <article key={nucleus.id} className="schools-educa-card"><div><small>{nucleus.code} · {nucleus.classification}</small><h2>{nucleus.name}</h2><p>{nucleus.activities.join(" · ") || "Sem atividades informadas"}</p></div><div className="schools-educa-card-metrics"><span>{nucleus.capacityPerShift} vagas/turno</span><span className={nucleus.status === "Ativo" ? "good" : "muted"}>{nucleus.status}</span><span>{nucleus.sportModalities.length ? "Esporte" : "Geral"}</span></div>{onEdit ? <button type="button" className="siga-icon-button" aria-label={`Editar ${nucleus.name}`} onClick={() => onEdit(nucleus)}><Pencil size={16} /></button> : reportMode ? <CheckCircle2 size={18} aria-label="Registro incluído no relatório" /> : null}</article>) : <p className="siga-empty-state">Nenhum núcleo encontrado para os filtros atuais.</p>}</div>; }
